DROP TABLE IF EXISTS APPLICATION_RELATED_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_TYPE;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_GROUP;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_GROUP_TYPE;
DROP TABLE IF EXISTS APPLICATION_FORM_FIELD;
DROP TABLE IF EXISTS APPLICATION_FORM_FIELD_TYPE;
DROP TABLE IF EXISTS APPLICATION_FORM;
DROP TABLE IF EXISTS APPLICATION_FORM_TYPE;
DROP TABLE IF EXISTS APPLICATION_ENTITY_FIELD;
DROP TABLE IF EXISTS APPLICATION_ENTITY_FIELD_TYPE;
DROP TABLE IF EXISTS APPLICATION_ENTITY;
DROP TABLE IF EXISTS APPLICATION_MODULE;
DROP TABLE IF EXISTS ADVICE;
DROP TABLE IF EXISTS ADVICE_STATUS;
DROP TABLE IF EXISTS ADVICE_TYPE_TAG;
DROP TABLE IF EXISTS ADVICE_TYPE;
DROP TABLE IF EXISTS SERVICE_TRANSACTION;
DROP TABLE IF EXISTS SERVICE_TRANSACTION_TYPE;
DROP TABLE IF EXISTS SERVICE_PEER;
DROP TABLE IF EXISTS HOST;
DROP TABLE IF EXISTS HOST_TYPE;
DROP TABLE IF EXISTS SERVICE;
DROP TABLE IF EXISTS SERVICE_MODE;
DROP TABLE IF EXISTS SERVICE_PROTOCOL_ADAPTER;
DROP TABLE IF EXISTS SERVICE_TYPE;
DROP TABLE IF EXISTS SERVICE_CATEGORY;
DROP TABLE IF EXISTS PAYMENT_APPLICATION;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS PAYMENT_TYPE;
DROP TABLE IF EXISTS PAYMENT_METHOD_TYPE_PROVIDER;
DROP TABLE IF EXISTS PAYMENT_METHOD_TYPE;
DROP TABLE IF EXISTS ORDER_ITEM_BILLING;
DROP TABLE IF EXISTS INVOICE_ITEM;
DROP TABLE IF EXISTS INVOICE_ITEM_CATEGORY;
DROP TABLE IF EXISTS INVOICE_ITEM_TYPE;
DROP TABLE IF EXISTS INVOICE_ROLE;
DROP TABLE IF EXISTS INVOICE_STATUS;
DROP TABLE IF EXISTS INVOICE;
DROP TABLE IF EXISTS INVOICE_TYPE;
DROP TABLE IF EXISTS INVOICE_TERM;
DROP TABLE IF EXISTS INVOICE_ROLE_TYPE;
DROP TABLE IF EXISTS INVOICE_STATUS_TYPE;
DROP TABLE IF EXISTS BILLING_ACCOUNT_ROLE;
DROP TABLE IF EXISTS BILLING_ACCOUNT;
DROP TABLE IF EXISTS BILLING_ACCOUNT_ROLE_TYPE;
DROP TABLE IF EXISTS TERM_TYPE;
DROP TABLE IF EXISTS UOM_CONVERSION;
DROP TABLE IF EXISTS UOM;
DROP TABLE IF EXISTS PRODUCT_ORDER_ITEM;
DROP TABLE IF EXISTS PRODUCT_ORDER_ITEM_TYPE;
DROP TABLE IF EXISTS PRODUCT_ORDER;
DROP TABLE IF EXISTS PRODUCT_ORDER_TYPE;
DROP TABLE IF EXISTS PRODUCT_COMPONENT;
DROP TABLE IF EXISTS ESTIMATED_PRODUCT_COST;
DROP TABLE IF EXISTS COST_COMPONENT_TYPE;
DROP TABLE IF EXISTS PRODUCT_FEATURE_APPLICABILITY;
DROP TABLE IF EXISTS PRODUCT_FEATURE_APPLICABILITY_TYPE;
DROP TABLE IF EXISTS PRODUCT_FEATURE;
DROP TABLE IF EXISTS PRODUCT_FEATURE_TYPE;
DROP TABLE IF EXISTS PRODUCT_FEATURE_CATEGORY;
DROP TABLE IF EXISTS PRODUCT_CLASSIFICATION;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRODUCT_TYPE;
DROP TABLE IF EXISTS PRODUCT_CATEGORY;
DROP TABLE IF EXISTS PRODUCT_CATEGORY_TYPE;
DROP TABLE IF EXISTS PARTY_CASE;
DROP TABLE IF EXISTS CASE_STATUS_TYPE;
DROP TABLE IF EXISTS CASE_ROLE;
DROP TABLE IF EXISTS CASE_ROLE_TYPE;
DROP TABLE IF EXISTS COMMUNICATION_EVENT_WORK_EFFORT;
DROP TABLE IF EXISTS COMMUNICATION_EVENT;
DROP TABLE IF EXISTS COMMUNICATION_EVENT_TYPE;
DROP TABLE IF EXISTS COMMUNICATION_EVENT_STATUS_TYPE;
DROP TABLE IF EXISTS WORK_EFFORT;
DROP TABLE IF EXISTS WORK_EFFORT_TYPE;
DROP TABLE IF EXISTS COMMUNICATION_EVENT_PURPOSE;
DROP TABLE IF EXISTS COMMUNICATION_EVENT_PURPOSE_TYPE;
DROP TABLE IF EXISTS POSTAL_ADDRESS_BOUNDRY;
DROP TABLE IF EXISTS PARTY_CONTACT_MECHANISM_PURPOSE;
DROP TABLE IF EXISTS CONTACT_MECHANISM_PURPOSE_TYPE;
DROP TABLE IF EXISTS PARTY_CONTACT_MECHANISM;
DROP TABLE IF EXISTS ELECTRONIC_ADDRESS;
DROP TABLE IF EXISTS TELECOMMUNICATIONS_NUMBER;
DROP TABLE IF EXISTS POSTAL_ADDRESS;
DROP TABLE IF EXISTS CONTACT_MECHANISM_LINK;
DROP TABLE IF EXISTS CONTACT_MECHANISM;
DROP TABLE IF EXISTS CONTACT_MECHANISM_TYPE;
DROP TABLE IF EXISTS CUSTOMER_BLACKLIST;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS PARTY_RELATIONSHIP;
DROP TABLE IF EXISTS PARTY_ROLE;
DROP TABLE IF EXISTS PARTY_CLASSIFICATION;
DROP TABLE IF EXISTS PERSON;
DROP TABLE IF EXISTS ORGANIZATION;
DROP TABLE IF EXISTS PARTY;
DROP TABLE IF EXISTS PARTY_TYPE;
DROP TABLE IF EXISTS PARTY_RELATIONSHIP_TYPE;
DROP TABLE IF EXISTS PARTY_CLASSIFICATION_TYPE;
DROP TABLE IF EXISTS PARTY_ROLE_TYPE;
DROP TABLE IF EXISTS ROLE_TYPE;
DROP TABLE IF EXISTS STATUS_TYPE;
DROP TABLE IF EXISTS GEO_BOUNDRY_ASSOCIATION;
DROP TABLE IF EXISTS GEO_BOUNDRY;
DROP TABLE IF EXISTS GEO_BOUNDARY_TYPE;
DROP TABLE IF EXISTS SERVICE_CHANNEL;
DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY ( 
	ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	CODE    				VARCHAR(3) NOT NULL,
	CRNCY_NM    			VARCHAR(35) NOT NULL,
	CRNCY_SYM   			VARCHAR(1) NULL,
	REMARKS        			VARCHAR(255) NULL,
	EFFECTIVE_DT   			DATE NOT NULL,
	REC_ST         			CHAR(1) NOT NULL,
	VERSION_NO     			INT(11) NULL,
	ROW_TS         			TIMESTAMP  NULL,
	CREATED_DT        		DATE NOT NULL,
	CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	LAST_MODIFIED_USR       VARCHAR(35) NULL,
	PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_CHANNEL (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(75) NOT  NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_CHL_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE GEO_BOUNDARY_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARENT_TY					INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARENT_TY) REFERENCES GEO_BOUNDARY_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE GEO_BOUNDRY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  GEO_BOUNDRY_TY_ID			INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  ABBREVIATION				VARCHAR(5) NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (GEO_BOUNDRY_TY_ID) REFERENCES GEO_BOUNDARY_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE GEO_BOUNDRY_ASSOCIATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  FROM_GEO_ID				INT(11) NOT NULL,
	  TO_GEO_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TO_GEO_ID) REFERENCES GEO_BOUNDRY (ID),
	  FOREIGN KEY (FROM_GEO_ID) REFERENCES GEO_BOUNDRY (ID)
)
ENGINE=InnoDB;

CREATE TABLE STATUS_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE ROLE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_ROLE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  ROLE_TY_ID				INT(11) NOT NULL,
	  PARENT_TY_ID				INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (ROLE_TY_ID) REFERENCES ROLE_TYPE (ID),
	  FOREIGN KEY (PARENT_TY_ID) REFERENCES PARTY_ROLE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_CLASSIFICATION_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARENT_TY_ID				INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARENT_TY_ID) REFERENCES PARTY_CLASSIFICATION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_RELATIONSHIP_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  FROM_ROLE_TY_ID			INT(11) NOT NULL,
	  TO_ROLE_TY_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TO_ROLE_TY_ID) REFERENCES PARTY_ROLE_TYPE (ID),
	  FOREIGN KEY (FROM_ROLE_TY_ID) REFERENCES PARTY_ROLE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARENT_TY_ID				INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARENT_TY_ID) REFERENCES PARTY_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_TY_ID				INT (11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_TY_ID) REFERENCES PARTY_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE ORGANIZATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID					INT (11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  TAX_ID_NO					VARCHAR(35) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID)
)
ENGINE=InnoDB;

CREATE TABLE PERSON (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  CURRENT_F_NM 				VARCHAR(75) NOT NULL,
	  CURRENT_L_NM 				VARCHAR(75) NULL,
	  CURRENT_M_NM				VARCHAR(75) NULL,	  
	  CURRENT_SUFFIX			VARCHAR(75) NULL,
	  CURRENT_PTITLE			VARCHAR(75) NULL,
	  CURRENT_N_NM				VARCHAR(75) NULL,
	  MOTHER_MAIDEN_NM			VARCHAR(75) NULL,
	  GENDER					VARCHAR(35) NOT NULL,
	  MARITAL_ST				VARCHAR(35) NULL,
	  SS_NO						VARCHAR(35) NULL,
	  CURRENT_PP_NO				VARCHAR(35) NULL,
	  CURRENT_PP_EXP_DT  		DATE NULL,
	  WEIGHT					DECIMAL(10,2) NULL,
	  HEIGHT					DECIMAL(10,2) NULL,
	  BIRTH_DT        			DATE NULL,
	  TOT_YR_WORK_EXP			INT(11) NULL,
	  REMARKS					VARCHAR(255) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_CLASSIFICATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CLASS_TY_ID				INT(11) NOT NULL,
	  PARTY_TY_ID				INT(11) NULL,
	  PARTY_ID					INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  FROM_DT        			DATE NOT NULL,
	  THRU_DT        			DATE NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (PARTY_TY_ID) REFERENCES PARTY_TYPE (ID),
	  FOREIGN KEY (CLASS_TY_ID) REFERENCES PARTY_CLASSIFICATION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_ROLE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  ROLE_TY_ID				INT(11) NULL,
	  PARTY_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  FROM_DT        			DATE NOT NULL,
	  THRU_DT        			DATE NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (ROLE_TY_ID) REFERENCES PARTY_ROLE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_RELATIONSHIP (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  RELATIONSHIP_TY_ID		INT(11) NOT NULL,
	  FROM_ROLE_ID				INT(11) NOT NULL,
	  TO_ROLE_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  COMMENT 					VARCHAR(255) NULL,
	  FROM_DT        			DATE NOT NULL,
	  THRU_DT        			DATE NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (FROM_ROLE_ID) REFERENCES PARTY_ROLE (ID),
	  FOREIGN KEY (FROM_ROLE_ID) REFERENCES PARTY_ROLE (ID),
	  FOREIGN KEY (RELATIONSHIP_TY_ID) REFERENCES PARTY_RELATIONSHIP_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID					INT (11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_BLACKLIST (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PARTY_ID					INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT  NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID),
	  UNIQUE INDEX CUSTOMER_BLACKLIST_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE CONTACT_MECHANISM_TYPE (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CONTACT_MECHANISM_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE CONTACT_MECHANISM (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CONT_MECH_TY_ID		INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CONTACT_MECHANISM_IX1 (CODE(35)),
	  FOREIGN KEY (CONT_MECH_TY_ID) REFERENCES CONTACT_MECHANISM_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE CONTACT_MECHANISM_LINK (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  FROM_ID				INT(11) NOT NULL,
	  TO_ID					INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CONTACT_MECHANISM_LINK_IX1 (CODE(35)),
	  FOREIGN KEY (FROM_ID) REFERENCES CONTACT_MECHANISM(ID),
	  FOREIGN KEY (TO_ID) REFERENCES CONTACT_MECHANISM(ID)
)
ENGINE=InnoDB;

CREATE TABLE POSTAL_ADDRESS (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CONT_MECH_ID			INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  ADDRESS1 				VARCHAR(150) NOT  NULL,
	  ADDRESS2 				VARCHAR(150) NOT  NULL,
	  DIRECTIONS 			VARCHAR(255) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX POSTAL_ADDRESS_IX1 (CODE(35)),
	  FOREIGN KEY (CONT_MECH_ID) REFERENCES CONTACT_MECHANISM(ID)
)
ENGINE=InnoDB;

CREATE TABLE TELECOMMUNICATIONS_NUMBER (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CONT_MECH_ID			INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  AREA_CODE 			VARCHAR(35) NULL,
	  CONTACT_NO 			VARCHAR(35) NOT  NULL,
	  COUNTRY_CD 			VARCHAR(35) NULL,
	  DESCRIPTION			VARCHAR(255) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TELECOMMUNICATIONS_NUMBER_IX1 (CODE(35)),
	  FOREIGN KEY (CONT_MECH_ID) REFERENCES CONTACT_MECHANISM(ID)
)
ENGINE=InnoDB;

CREATE TABLE ELECTRONIC_ADDRESS (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CONT_MECH_ID			INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  ELEC_ADDR_TXT 		VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(255) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ELECTRONIC_ADDRESS_IX1 (CODE(35)),
	  FOREIGN KEY (CONT_MECH_ID) REFERENCES CONTACT_MECHANISM(ID)
)
ENGINE=InnoDB;

CREATE TABLE PARTY_CONTACT_MECHANISM (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CONT_MECH_ID			INT(11) NOT NULL,
	  PARTY_ID				INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  FROM_DT        		DATE NOT NULL,
	  TO_DT        			DATE NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  NO_SOLICITATION_FG	char(1) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  EXTENSION        		VARCHAR(35) NULL,
	  REMARKS        		VARCHAR(255) NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ELECTRONIC_ADDRESS_IX1 (CODE(35)),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY(ID),
	  FOREIGN KEY (CONT_MECH_ID) REFERENCES CONTACT_MECHANISM(ID)
)
ENGINE=InnoDB;

CREATE TABLE CONTACT_MECHANISM_PURPOSE_TYPE (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CONTACT_MECHANISM_PURPOSE_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB; 

CREATE TABLE PARTY_CONTACT_MECHANISM_PURPOSE (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  CONT_MECH_ID			INT(11) NOT NULL,
	  MECH_PURPOSE_TY_ID	INT(11) NOT NULL,
	  FROM_DT        		DATE NOT NULL,
	  TO_DT        			DATE NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CONTACT_MECHANISM_PURPOSE_TYPE_IX1 (CODE(35)),
	  FOREIGN KEY (CONT_MECH_ID) REFERENCES CONTACT_MECHANISM(ID),
	  FOREIGN KEY (MECH_PURPOSE_TY_ID) REFERENCES CONTACT_MECHANISM_PURPOSE_TYPE(ID)
)
ENGINE=InnoDB;

CREATE TABLE POSTAL_ADDRESS_BOUNDRY (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  POSTAL_ADDR_ID		INT(11) NOT NULL,
	  GEO_BOUNDRY_ID		INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX POSTAL_ADDRESS_BOUNDRY_IX1 (CODE(35)),
	  FOREIGN KEY (GEO_BOUNDRY_ID) REFERENCES GEO_BOUNDRY(ID),
	  FOREIGN KEY (POSTAL_ADDR_ID) REFERENCES POSTAL_ADDRESS(ID)
)
ENGINE=InnoDB;

CREATE TABLE COMMUNICATION_EVENT_PURPOSE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150)  NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX COMMUNICATION_EVENT_PURPOSE_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE COMMUNICATION_EVENT_PURPOSE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PURPOSE_TYPE_ID			INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PURPOSE_TYPE_ID) REFERENCES COMMUNICATION_EVENT_PURPOSE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE COMMUNICATION_EVENT_STATUS_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE WORK_EFFORT_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),	  
	  UNIQUE INDEX WORK_EFFORT_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE WORK_EFFORT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  WORK_EFFORT_TY_ID			INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  SCHED_START_DT        	DATE NOT NULL,
	  SCHED_END_DT        		DATE NOT NULL,
	  EST_HOURS		 			INT(11) NULL,
	  TOTAL_HR_ALLOWED 			INT(11) NULL,
	  TOTAL_AMOUNT_ALLOWED		DECIMAL(38,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)  ,
	  FOREIGN KEY (WORK_EFFORT_TY_ID) REFERENCES WORK_EFFORT_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE COMMUNICATION_EVENT_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),	  
	  UNIQUE INDEX COMMUNICATION_EVENT_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE COMMUNICATION_EVENT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  EVENT_TY_ID				INT(11) NOT NULL,
	  EVENT_PURPOSE_ID			INT(11) NOT NULL,
	  EVENT_ST_TY_ID			INT(11) NOT NULL,
	  PARTY_REL_ID				INT(11) NULL,
	  CONTACT_MECH_TY_ID		INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  SUBJECT 					VARCHAR(150) NULL,
	  CONTENT 					TEXT NULL,
	  FROM_EMAIL				VARCHAR(35) NULL,
	  TO_EMAIL					VARCHAR(35) NULL,
	  FROM_PHONE				VARCHAR(35) NULL,
	  TO_PHONE					VARCHAR(35) NULL,
	  START_DT        			TIMESTAMP NULL,
	  END_DT        			TIMESTAMP NULL,
	  NOTE		 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_REL_ID) REFERENCES PARTY_RELATIONSHIP (ID),
	  FOREIGN KEY (EVENT_TY_ID) REFERENCES COMMUNICATION_EVENT_TYPE (ID),
	  FOREIGN KEY (CONTACT_MECH_TY_ID) REFERENCES CONTACT_MECHANISM_TYPE (ID),
	  FOREIGN KEY (EVENT_PURPOSE_ID) REFERENCES COMMUNICATION_EVENT_PURPOSE (ID),
	  FOREIGN KEY (EVENT_ST_TY_ID) REFERENCES COMMUNICATION_EVENT_STATUS_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE COMMUNICATION_EVENT_WORK_EFFORT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  COMM_EVENT_ID				INT(11) NOT NULL,
	  WORK_EFFORT_ID			INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),	
	  FOREIGN KEY (WORK_EFFORT_ID) REFERENCES WORK_EFFORT (ID),
	  FOREIGN KEY (COMM_EVENT_ID) REFERENCES COMMUNICATION_EVENT (ID)
)
ENGINE=InnoDB;

CREATE TABLE CASE_ROLE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),	  
	  UNIQUE INDEX CASE_ROLE_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE CASE_ROLE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CASE_ROLE_TY_ID			INT(11) NOT NULL,
	  PARTY_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID) ,
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (CASE_ROLE_TY_ID) REFERENCES CASE_ROLE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CASE_STATUS_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),	  
	  UNIQUE INDEX CASE_STATUS_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PARTY_CASE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CASE_ST_ID				INT(11) NOT NULL,
	  CASE_ROLE_ID				INT(11) NOT NULL,
	  COMM_EVENT_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CASE_ROLE_ID) REFERENCES CASE_ROLE (ID),
	  FOREIGN KEY (CASE_ST_ID) REFERENCES CASE_STATUS_TYPE (ID),
	  FOREIGN KEY (COMM_EVENT_ID) REFERENCES COMMUNICATION_EVENT (ID)
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_CATEGORY_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_CATEGORY_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_CATEGORY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PROD_CAT_TY_ID 			INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_CATEGORY_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_CAT_TY_ID) REFERENCES PRODUCT_CATEGORY_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAMES 					VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_TYPE_IX1 (CODE(35))

)
ENGINE=InnoDB;

CREATE TABLE PRODUCT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PROD_TY_ID 				INT (11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  INTRODUCTION_DT        	DATE NOT NULL,
	  DISCOUNTINUED_DT        	DATE NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_TY_ID) REFERENCES PRODUCT_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_CLASSIFICATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PROD_ID					INT(11) NOT NULL,
	  PROD_CAT_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150)  NULL,
	  REMARKS 					VARCHAR(255)  NULL,
	  FROM_DT        			DATE NOT NULL,
	  TO_DT        				DATE NOT NULL,
	  PRIMARY_FG         		CHAR(1) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_CLASSIFICATION_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (ID),
	  FOREIGN KEY (PROD_CAT_ID) REFERENCES PRODUCT_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_FEATURE_CATEGORY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_FEATURE_CATEGORY_IX1 (CODE(35))

)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_FEATURE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_FEATURE_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_FEATURE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PROD_FEAT_CAT				INT(11) NOT NULL,
	  PROD_FEAT_TY				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_FEATURE_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_FEAT_TY) REFERENCES PRODUCT_FEATURE_TYPE (ID),
	  FOREIGN KEY (PROD_FEAT_CAT) REFERENCES PRODUCT_FEATURE_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_FEATURE_APPLICABILITY_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_FEATURE_APPLICABILITY_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_FEATURE_APPLICABILITY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  APPLICABITY_TY_ID			INT(11) NOT NULL,
	  PROD_FEAT_ID				INT(11) NOT NULL,
	  PROD_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  FROM_DT        			DATE NOT NULL,
	  TO_DT        				DATE NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_FEATURE_APPLICABILITY_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (ID),
	  FOREIGN KEY (PROD_FEAT_ID) REFERENCES PRODUCT_FEATURE (ID),
	  FOREIGN KEY (APPLICABITY_TY_ID) REFERENCES PRODUCT_FEATURE_APPLICABILITY_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE COST_COMPONENT_TYPE(
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX COST_COMPONENT_TYPE_IX1 (CODE(35))
)ENGINE=InnoDB;

CREATE TABLE ESTIMATED_PRODUCT_COST(
 	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  COST_COMP_TY_ID			INT(11) NOT NULL,
	  PROD_FEAT_ID				INT(11) NULL,
	  PROD_ID					INT(11) NULL,
	  GEO_BOUNDRY_ID			INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  COST 						DECIMAL(38, 2) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  FROM_DT        			DATE NOT NULL,
	  TO_DT        				DATE NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX ESTIMATED_PRODUCT_COST_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (ID),
	  FOREIGN KEY (GEO_BOUNDRY_ID) REFERENCES GEO_BOUNDRY (ID),
	  FOREIGN KEY (PROD_FEAT_ID) REFERENCES PRODUCT_FEATURE (ID),
	  FOREIGN KEY (COST_COMP_TY_ID) REFERENCES COST_COMPONENT_TYPE (ID)
)ENGINE=InnoDB;

CREATE TABLE PRODUCT_COMPONENT(
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  IN_PROD_ID				INT(11) NOT NULL,
	  FOR_PROD_ID				INT(11) NULL,
	  LOCATION_ID				INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  INSTRUCTION 				TEXT NULL,
	  REMARKS 					VARCHAR(255) NULL,
	  QUANTITIY_USED			INT(11) NULL,
	  FROM_DT        			DATE NOT NULL,
	  TO_DT        				DATE NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_COMPONENT_IX1 (CODE(35)),
	  FOREIGN KEY (IN_PROD_ID) REFERENCES PRODUCT (ID),
	  FOREIGN KEY (FOR_PROD_ID) REFERENCES PRODUCT (ID)
)ENGINE=InnoDB;

CREATE TABLE PRODUCT_ORDER_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME		 				VARCHAR(75) NOT NULL,
	  DESCRIPTION	 			VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_ORDER_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_ORDER (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PROD_ORD_TY_ID			INT (11) NOT NULL,
	  FROM_PARTY_ID				INT (11) NOT NULL,
	  TO_PARTY_ID				INT (11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  ORDER_DT					DATE NOT NULL,
	  AMOUNT					DECIMAL (38,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TO_PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (FROM_PARTY_ID) REFERENCES PARTY (ID),
	  UNIQUE INDEX PRODUCT_ORDER_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_ORD_TY_ID) REFERENCES PRODUCT_ORDER_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_ORDER_ITEM_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME		 				VARCHAR(75) NOT NULL,
	  DESCRIPTION	 			VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_ORDER_ITEM_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PRODUCT_ORDER_ITEM (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PROD_ORD_TY_ID			INT(11) NOT NULL,
	  PROD_ORD_ID				INT(11) NOT NULL,
	  PROD_ID 					INT (11)  NULL,
	  PROD_FEAT_ID				INT (11)  NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  QUANTITY					INT (11) NOT NULL,
	  UNIT_PRICE				DECIMAL (38, 2)  NULL,
	  EXPECT_DELIVERY_DT		DATE NULL,
	  INSTRUCTIONS				TEXT NULL,
	  REMARKS					VARCHAR(255) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PRODUCT_ORDER_ITEM_IX1 (CODE(35)),
	  FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (ID),
	  FOREIGN KEY (PROD_ORD_ID) REFERENCES PRODUCT_ORDER (ID),
	  FOREIGN KEY (PROD_FEAT_ID) REFERENCES PRODUCT_FEATURE (ID),
	  FOREIGN KEY (PROD_ORD_TY_ID) REFERENCES PRODUCT_ORDER_ITEM_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE UOM (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX UOM_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE UOM_CONVERSION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  FROM_UOM_ID				INT(11) NOT NULL,
	  TO_UOM_ID					INT(11) NOT NULL,
	  CONVERSION_FACTOR			INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX UOM_CONVERSION_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE TERM_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX TERM_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE BILLING_ACCOUNT_ROLE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX BILLING_ACCOUNT_ROLE_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE BILLING_ACCOUNT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CONT_MECH_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  FROM_DT        			DATE NOT NULL,
	  THRU_DT        			DATE NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX BILLING_ACCOUNT_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE BILLING_ACCOUNT_ROLE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  ROLE_TY_ID				INT(11) NOT NULL,
	  PARTY_ID					INT(11) NOT NULL,
	  ACCOUNT_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  FROM_DT        			DATE NOT NULL,
	  THRU_DT        			DATE NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (ACCOUNT_ID) REFERENCES BILLING_ACCOUNT (ID),
	  FOREIGN KEY (ROLE_TY_ID) REFERENCES BILLING_ACCOUNT_ROLE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_STATUS_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX INVOICE_STATUS_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_ROLE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX INVOICE_ROLE_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_TERM (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  TERM_TY_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  TERM_VAL 					DECIMAL(38,2) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TERM_TY_ID) REFERENCES TERM_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX INVOICE_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE INVOICE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  INVOICE_TY_ID				INT(11) NOT NULL,
	  INVOICE_TERM_ID			INT(11) NULL,
	  FROM_PARTY_ID				INT(11) NOT NULL,
	  TO_PARTY_ID				INT(11) NOT NULL,
	  CONT_MECH_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  MESSAGE 					VARCHAR(255) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  INVOICE_DT        		DATE NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TO_PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (FROM_PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (INVOICE_TY_ID) REFERENCES INVOICE_TYPE (ID),
	  FOREIGN KEY (INVOICE_TERM_ID) REFERENCES INVOICE_TERM (ID),
	  FOREIGN KEY (CONT_MECH_ID) REFERENCES CONTACT_MECHANISM (ID)
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_STATUS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  INVOICE_ID				INT(11) NOT NULL,
	  INVOICE_ST_TY_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID),
	  FOREIGN KEY (INVOICE_ST_TY_ID) REFERENCES INVOICE_STATUS_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_ROLE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  INVOICE_ID				INT(11) NOT NULL,
	  INVOICE_ROLE_TY_ID		INT(11) NOT NULL,
	  PARTY_ID					INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  PERCENTAGE 				INT(3) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID),
	  FOREIGN KEY (INVOICE_ROLE_TY_ID) REFERENCES INVOICE_ROLE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_ITEM_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX INVOICE_ITEM_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_ITEM_CATEGORY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX INVOICE_ITEM_CATEGORY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE INVOICE_ITEM (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  INVOICE_ID				INT(11) NOT NULL,
	  ITEM_CAT_ID				INT(11) NOT NULL,
	  ITEM_TY_ID				INT(11) NOT NULL,
	  PROD_ID					INT(11) NULL,
	  PROD_FEAT_ID				INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  TAXABLE_FG         		CHAR(1) NULL,
	  QUANTITY         			INT(11) NOT NULL,
	  AMOUNT         			DECIMAL(38,2) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (INVOICE_ID) REFERENCES INVOICE (ID),
	  FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (ID),
	  FOREIGN KEY (PROD_FEAT_ID) REFERENCES PRODUCT_FEATURE (ID),
	  FOREIGN KEY (ITEM_TY_ID) REFERENCES INVOICE_ITEM_TYPE (ID),
	  FOREIGN KEY (ITEM_CAT_ID) REFERENCES INVOICE_ITEM_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE ORDER_ITEM_BILLING (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  ORDER_ITEM_ID				INT(11) NOT NULL,
	  INVOICE_ITEM_ID			INT(11) NOT NULL,
	  QUANTITY					INT(11) NOT NULL,
	  AMOUNT					DECIMAL(38,2) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (INVOICE_ITEM_ID) REFERENCES INVOICE_ITEM (ID),
	  FOREIGN KEY (ORDER_ITEM_ID) REFERENCES PRODUCT_ORDER_ITEM (ID)
)
ENGINE=InnoDB;

CREATE TABLE PAYMENT_METHOD_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PAYMENT_METHOD_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PAYMENT_METHOD_TYPE_PROVIDER (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PAYMENT_METH_TY_ID		INT(11) NOT NULL,
	  PROVIDER_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  FROM_DT        			DATE NOT NULL,
	  THRU_DT        			DATE NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PROVIDER_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (PAYMENT_METH_TY_ID) REFERENCES PAYMENT_METHOD_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE PAYMENT_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX PAYMENT_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE PAYMENT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PAYMENT_TY_ID				INT(11) NOT NULL,
	  PAYMENT_METHOD_TY_ID		INT(11) NOT NULL,
	  PAYMNT_PROV_METH_TY_ID	INT(11) NULL,
	  FROM_PARTY_ID				INT(11) NOT NULL,
	  TO_PARTY_ID				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  COMMENT	 				VARCHAR(255) NULL,
	  AMOUNT 					DECIMAL(38,2) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (TO_PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (FROM_PARTY_ID) REFERENCES PARTY (ID),
	  FOREIGN KEY (PAYMENT_TY_ID) REFERENCES PAYMENT_TYPE (ID),
	  FOREIGN KEY (PAYMENT_METHOD_TY_ID) REFERENCES PAYMENT_METHOD_TYPE (ID),
	  FOREIGN KEY (PAYMNT_PROV_METH_TY_ID) REFERENCES PAYMENT_METHOD_TYPE_PROVIDER(ID)
)
ENGINE=InnoDB;

CREATE TABLE PAYMENT_APPLICATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  PAYMENT_ID				INT(11) NOT NULL,
	  INVOICE_ITEM_ID			INT(11) NULL,
	  BILLING_ACCT_ID			INT(11) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  DESCRIPTION 				VARCHAR(150) NULL,
	  AMOUNT_APPL 				DECIMAL(38,2) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT (ID),
	  FOREIGN KEY (INVOICE_ITEM_ID) REFERENCES INVOICE_ITEM (ID),
	  FOREIGN KEY (BILLING_ACCT_ID) REFERENCES BILLING_ACCOUNT (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  REQ_FEEDBACK			CHAR(1) NULL,
	  FEEDBACK_MSG			VARCHAR(255) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_TYPE_TAG (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  ADVICE_TY_ID 			INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  ADVICE_TY_TAG_VAL 	TEXT NOT  NULL,
	  IS_REGEX_FG         	char(1) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_TY_TAG_IX1 (CODE(35)),
	  FOREIGN KEY (ADVICE_TY_ID) REFERENCES ADVICE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_STATUS (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_ST_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE ADVICE (
	  ID				 		INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT  NULL,
	  NAME 						VARCHAR(75) NOT  NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  COMM_EVENT_ID				INT (11) NOT NULL,
	  ADVICE_TY_ID				INT (11) NOT NULL,
	  ADVICE_ST_ID				INT (11) NOT NULL,
	  CUSTOMER_ID				INT (11) NOT NULL,
	  ADVICE_TXT		    	TEXT NULL,
	  CARD_NO				    VARCHAR(35) NULL,
	  ACCOUNT_NO				VARCHAR(35) NOT NULL,
	  CHEQUE_NO					VARCHAR(35) NULL,
	  ACCOUNT_NM				VARCHAR(75) NULL,
	  AMOUNT 					DECIMAL(38,2) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (COMM_EVENT_ID) REFERENCES COMMUNICATION_EVENT (ID),
	  FOREIGN KEY (ADVICE_TY_ID) REFERENCES ADVICE_TYPE (ID),
	  FOREIGN KEY (ADVICE_ST_ID) REFERENCES ADVICE_STATUS (ID),
	  FOREIGN KEY (CUSTOMER_ID) REFERENCES PARTY (ID),
	  UNIQUE INDEX ADVICE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_CATEGORY (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_CATEGORY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_PROTOCOL_ADAPTER (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(50) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  CLASS_NAME 			VARCHAR(150) NOT  NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_PROTOCOL_ADAPTER_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_MODE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_MODE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  SERVICE_TY_ID		 	INT (11)  NOT NULL,
	  SERVICE_CATEGORY_ID	INT (11)  NOT NULL,
	  MODE_ID		 		INT (11)  NOT NULL,
	  ADAPTER_ID		 	INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  PORT_NO				INT(6) NOT NULL,
	  IP_ADDRESS			VARCHAR(15) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_IX1 (CODE(35)),
	  FOREIGN KEY (SERVICE_TY_ID) REFERENCES SERVICE_TYPE (ID),
	  FOREIGN KEY (SERVICE_CATEGORY_ID) REFERENCES SERVICE_CATEGORY (ID),
	  FOREIGN KEY (MODE_ID) REFERENCES SERVICE_MODE (ID),
	  FOREIGN KEY (ADAPTER_ID) REFERENCES SERVICE_PROTOCOL_ADAPTER (ID)
)
ENGINE=InnoDB;

CREATE TABLE HOST_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX HOST_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE HOST (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  HOST_TY_ID		 	INT (11)  NOT NULL,
	  ADAPTER_ID		 	INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  PORT_NO				INT(16) NOT NULL,
	  IP_ADDRESS			VARCHAR(15) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX HOST_IX1 (CODE(35)),
	  FOREIGN KEY (HOST_TY_ID) REFERENCES HOST_TYPE (ID),
	  FOREIGN KEY (ADAPTER_ID) REFERENCES SERVICE_PROTOCOL_ADAPTER (ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_PEER (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  SERVICE_ID			INT(11) NOT NULL,
	  HOST_ID				INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_PEER_IX1 (CODE(35)),
	  UNIQUE INDEX SERVICE_PEER_IX2 (SERVICE_ID, HOST_ID),
	  FOREIGN KEY (HOST_ID) REFERENCES HOST (ID),
	  FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TRANSACTION_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  TXN_TY_ID				INT(11) NOT NULL,
	  SERVICE_ID			INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  AMOUNT				DECIMAL(38, 2) NOT NULL,
	  TXN_DATE				DATE NOT NULL,
	  ACCOUNT_NO			VARCHAR(75) NOT NULL,
	  ACCOUNT_NM			VARCHAR(75) NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TXN_IX1 (CODE(35)),
	  FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (ID),
	  FOREIGN KEY (TXN_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_MODULE (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  SEQUENCE_NO 			INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(50) NOT  NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  DISPLAY_FG 			CHAR (1)  NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX APPLICATION_MODULE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(150) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_NM_PLURAL		VARCHAR(75) NOT  NULL,
	  HAS_TABLE				CHAR(1) NOT  NULL,
	  DB_NAME				CHAR(50) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  UNIQUE INDEX APPLICATION_ENTITY_U01 (CODE(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY_FIELD_TYPE
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY_FIELD
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  FIELD_TY_ID			INT(11) NOT NULL,
	  ENTITY_ID 			INT(11)  NOT NULL,
	  RELATED_ENTITY_ID		INT(11)  NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  PRIMARYKEY_FG			CHAR(1) NOT NULL,
	  STORAGE				CHAR(35) NOT NULL,
	  REQUIRED_FG			CHAR(1) NOT NULL,
	  UNIQUE_FG				CHAR(1) NULL,
	  RELATED_FG			CHAR(1) NULL,
	  SIZE					INT(11) NULL,
	  MAX_DIGITS			INT(11) NULL,
	  DECIMAL_PRECISION		INT(11) NULL,
	  SEQUENCE_NO			INT(11) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_IX1 (CODE(75)),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (RELATED_ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (FIELD_TY_ID) REFERENCES APPLICATION_ENTITY_FIELD_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_TYPE
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FORM_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_ENTITY_FORM_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID				INT (11)  NOT NULL,
	  FORM_TY_ID			INT (11)  NOT NULL,
	  ENTITY_ID				INT (11)  NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_NM_PLURAL		VARCHAR(75) NOT  NULL,
	  HAS_TABLE				CHAR(1) NOT  NULL,
	  DB_NAME				CHAR(50) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (FORM_TY_ID) REFERENCES APPLICATION_FORM_TYPE (ID),
	  UNIQUE INDEX APPLICATION_FORM_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_FIELD_TYPE
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_FORM_FIELD_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_FORM_FIELD_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_FIELD
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  FIELD_TY_ID			INT(11) NOT NULL,
	  FORM_ID 				INT(11) NOT NULL,
	  ENTITY_FIELD_ID		INT(11) NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  PRIMARYKEY_FG			CHAR(1) NOT NULL,
	  REQUIRED_FG			CHAR(1) NOT NULL,
	  RELATED_FG			CHAR(1) NULL,
	  SIZE					INT(11) NULL,
	  MAX_DIGITS			INT(11) NULL,
	  DECIMAL_PRECISION		INT(11) NULL,
	  SEQUENCE_NO			INT(11) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_IX1 (CODE(75)),
	  FOREIGN KEY (FORM_ID) REFERENCES APPLICATION_FORM (ID),
	  FOREIGN KEY (FIELD_TY_ID) REFERENCES APPLICATION_FORM_FIELD_TYPE (ID),
	  FOREIGN KEY (ENTITY_FIELD_ID) REFERENCES APPLICATION_ENTITY_FIELD (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_GROUP_TYPE
(
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ACT_GRP_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_GROUP (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  PARENT_GRP_ID     	INT (11)  NULL,
	  GRP_TY_ID				INT (11) NOT NULL,
	  CODE 					VARCHAR(50) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  GRP_URL			    VARCHAR(255) NOT NULL,
	  GRP_SEQ 				INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  DISPLAY_FG 			CHAR (1)  NOT NULL,
	  IS_PARENT         	CHAR(1) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (PARENT_GRP_ID) REFERENCES APPLICATION_ACTIVITY_GROUP (ID),
	  FOREIGN KEY (GRP_TY_ID) REFERENCES APPLICATION_ACTIVITY_GROUP_TYPE (ID),
	  UNIQUE INDEX APPLICATION_ACT_GRP_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ACT_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  GRP_ID 			    INT (11)  NOT NULL,
	  ACTIVITY_TY_ID		INT (11)  NOT NULL,
	  ENTITY_ID 			INT (11)  NULL,
	  FORM_ID				INT (11)  NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(150) NOT  NULL,
	  DESCRIPTION			VARCHAR(100) NULL,
	  ACTIVITY_URL		    VARCHAR(255) NULL,
	  ACTIVITY_SEQ 			INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  OPERATION_CD 			VARCHAR(35) NOT  NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	        DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (GRP_ID) REFERENCES APPLICATION_ACTIVITY_GROUP (ID),
	  FOREIGN KEY (FORM_ID) REFERENCES APPLICATION_FORM (ID),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (ACTIVITY_TY_ID) REFERENCES APPLICATION_ACTIVITY_TYPE (ID),
	  UNIQUE INDEX APPLICATION_ACTIVITY_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_RELATED_ACTIVITY (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  SRC_ACT_ID 			INT (11)  NULL,
	  DST_ACT_ID 			INT (11)  NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  REL_ACT_SEQ 			INT (11)  NOT NULL DEFAULT 0,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (SRC_ACT_ID) REFERENCES APPLICATION_ACTIVITY (ID),
	  FOREIGN KEY (DST_ACT_ID) REFERENCES APPLICATION_ACTIVITY (ID),
	  UNIQUE INDEX RELATED_ACTIVITY_U01 (SRC_ACT_ID, DST_ACT_ID)
)
ENGINE=InnoDB;
