DROP TABLE IF EXISTS CURRENT_USER_SESSION;
DROP TABLE IF EXISTS SYSTEM_USER_GROUP;
DROP TABLE IF EXISTS SYSTEM_USER_NOTIFICATION_CHANNEL;
DROP TABLE IF EXISTS SYSTEM_USER_NOTIFICATION;
DROP TABLE IF EXISTS SYSTEM_USER_MESSAGE;
DROP TABLE IF EXISTS SYSTEM_USER;
DROP TABLE IF EXISTS SYSTEM_GROUP;
DROP TABLE IF EXISTS TEMP_RELATED_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_RELATED_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_TYPE;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_GROUP;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_GROUP_TYPE;
DROP TABLE IF EXISTS APPLICATION_FORM_FIELD;
DROP TABLE IF EXISTS APPLICATION_FORM_FIELD_TYPE;
DROP TABLE IF EXISTS APPLICATION_FORM;
DROP TABLE IF EXISTS APPLICATION_FORM_TYPE;
DROP TABLE IF EXISTS APPLICATION_ENTITY_FIELD;
DROP TABLE IF EXISTS APPLICATION_ENTITY_FIELD_TYPE;
DROP TABLE IF EXISTS APPLICATION_ENTITY;
DROP TABLE IF EXISTS APPLICATION_MODULE;
DROP TABLE IF EXISTS DATA_INPUT_JOB_RECORDS_SUMMARY;
DROP TABLE IF EXISTS DATA_INPUT_JOB_RECORDS_SUMMARY_STATUS;
DROP TABLE IF EXISTS DATA_INPUT_JOB_SUMMARY;
DROP TABLE IF EXISTS DATA_INPUT_JOB_SUMMARY_STATUS;
DROP TABLE IF EXISTS CELL_DATA;
DROP TABLE IF EXISTS ROW_DATA;
DROP TABLE IF EXISTS TABLE_DATA;
DROP TABLE IF EXISTS DATA_INPUT_JOB;
DROP TABLE IF EXISTS DATA_INPUT_JOB_STATUS;
DROP TABLE IF EXISTS DATA_INPUT_JOB_TYPE;
DROP TABLE IF EXISTS DATA_INPUT_PROCESSORS;
DROP TABLE IF EXISTS DATA_INPUT;
DROP TABLE IF EXISTS DATA;
DROP TABLE IF EXISTS DATA_TYPE;
DROP TABLE IF EXISTS DATA_FIELD;
DROP TABLE IF EXISTS DATA_FIELD_TYPE;
DROP TABLE IF EXISTS DATA_STRUCTURE;;
DROP TABLE IF EXISTS DATA_TRANSFORMER;
DROP TABLE IF EXISTS DATA_LOADER;
DROP TABLE IF EXISTS DATA_PROCESSOR;
DROP TABLE IF EXISTS DATA_EXTRACTOR;
DROP TABLE IF EXISTS ADVICED_TRANSACTION;
DROP TABLE IF EXISTS ADVICE;
DROP TABLE IF EXISTS ADVICE_STATUS;
DROP TABLE IF EXISTS ADVICE_TYPE_TAG;
DROP TABLE IF EXISTS ADVICE_TYPE;
DROP TABLE IF EXISTS ADVICE_CLASSIFICATION;
DROP TABLE IF EXISTS ADVICE_REQUEST_MESSAGE;
DROP TABLE IF EXISTS ADVICE_REQUEST_MESSAGE_STATUS;
DROP TABLE IF EXISTS CUSTOMER_MESSAGE;
DROP TABLE IF EXISTS MESSAGE_ACTION;
DROP TABLE IF EXISTS MESSAGE_ATTACHMENT;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS MESSAGE_APPLICATION_NOTIFICATION_MAP;
DROP TABLE IF EXISTS MESSAGE_APPLICATION_ACTION_TAG;
DROP TABLE IF EXISTS MESSAGE_APPLICATION_ACTION;
DROP TABLE IF EXISTS MESSAGE_APPLICATION_TAG;
DROP TABLE IF EXISTS MESSAGE_APPLICATION;
DROP TABLE IF EXISTS MESSAGE_CLASSIFICATION;
DROP TABLE IF EXISTS MESSAGE_STATUS;
DROP TABLE IF EXISTS MESSAGE_TYPE;
DROP TABLE IF EXISTS MESSAGE_CATEGORY;
DROP TABLE IF EXISTS CUSTOMER_NOTIFICATION_CHANNEL;
DROP TABLE IF EXISTS CUSTOMER_TYPE_NOTIFICATION_CHANNEL;
DROP TABLE IF EXISTS CUSTOMER_CATEGORY_NOTIFICATION_CHANNEL;
DROP TABLE IF EXISTS CUSTOMER_CLASSIFICATION_NOTIFICATION_CHANNEL;
DROP TABLE IF EXISTS CUSTOMER_TRANSACTION_LIMIT;
DROP TABLE IF EXISTS CUSTOMER_TYPE_TRANSACTION_LIMIT;
DROP TABLE IF EXISTS CUSTOMER_CLASSIFICATION_TRANSACTION_LIMIT;
DROP TABLE IF EXISTS CUSTOMER_CATEGORY_TRANSACTION_LIMIT;
DROP TABLE IF EXISTS TXN_AWAITING_NOTIFICATION;
DROP TABLE IF EXISTS TXN_AWAITING_CONFIRMATION;
DROP TABLE IF EXISTS TXN_NOTIFICATION_STATUS;
DROP TABLE IF EXISTS TXN_CONFIRMATION_STATUS;
DROP TABLE IF EXISTS CUST_TXN_TYPE_CONFIRMATION_OPTIONS;
DROP TABLE IF EXISTS CUST_TYPE_TXN_TYPE_CONFIRMATION_OPTIONS;
DROP TABLE IF EXISTS CUST_CAT_TXN_TYPE_CONFIRMATION_OPTIONS;
DROP TABLE IF EXISTS CUST_TXN_TYPE_NOTIFICATION_OPTIONS;
DROP TABLE IF EXISTS CUST_TYPE_TXN_TYPE_NOTIFICATION_OPTIONS;
DROP TABLE IF EXISTS CUST_CAT_TXN_TYPE_NOTIFICATION_OPTIONS;
DROP TABLE IF EXISTS SERVICE_TRANSACTION;
DROP TABLE IF EXISTS SERVICE_TRANSACTION_STATUS;
DROP TABLE IF EXISTS SERVICE_TRANSACTION_TYPE;
DROP TABLE IF EXISTS SERVICE_TRANSACTION_CATEGORY;
DROP TABLE IF EXISTS DATA_CHANNEL;
DROP TABLE IF EXISTS DATA_CHANNEL_STATUS;
DROP TABLE IF EXISTS DATA_CHANNEL_TYPE;
DROP TABLE IF EXISTS DATA_CHANNEL_ADAPTER;
DROP TABLE IF EXISTS DATA_CHANNEL_CATEGORY;
DROP TABLE IF EXISTS CUSTOMER_NOTIFICATION;
DROP TABLE IF EXISTS NOTIFICATION_TYPE;
DROP TABLE IF EXISTS NOTIFICATION_CATEGORY;
DROP TABLE IF EXISTS TEMPLATE;
DROP TABLE IF EXISTS TEMPLATE_TYPE_TAG;
DROP TABLE IF EXISTS TEMPLATE_TYPE;
DROP TABLE IF EXISTS TEMPLATE_CATEGORY;
DROP TABLE IF EXISTS TEMPLATE_CLASSIFICATION;
DROP TABLE IF EXISTS CUSTOMER_BLACKLIST;
DROP TABLE IF EXISTS LIMIT_TYPE;
DROP TABLE IF EXISTS CUSTOMER_ACCOUNT;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ACCOUNT_TYPE;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CUSTOMER_TYPE;
DROP TABLE IF EXISTS CUSTOMER_CATEGORY;
DROP TABLE IF EXISTS CUSTOMER_CLASSIFICATION;
DROP TABLE IF EXISTS BUSINESS_UNIT;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY ( 
	ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	CODE    				VARCHAR(3) NOT NULL,
	NAME	    			VARCHAR(35) NOT NULL,
	CRNCY_SYM   			VARCHAR(1) NULL,
	REMARKS        			VARCHAR(255) NULL,
	EFFECTIVE_DT   			DATE NOT NULL,
	REC_ST         			CHAR(1) NOT NULL,
	VERSION_NO     			INT(11) NULL,
	ROW_TS         			TIMESTAMP  NULL,
	CREATED_DT        		DATE NOT NULL,
	CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	LAST_MODIFIED_USR       VARCHAR(35) NULL,
	PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE COUNTRY ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(3) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  CNTRY_CD_ISO2 		VARCHAR(2) NOT NULL,
	  CNTRY_CD_ISO3 		VARCHAR(3) NULL,
	  LOCAL_CRNCY_ID		INT(11) NULL,
	  REMARKS        		VARCHAR(255) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (LOCAL_CRNCY_ID) REFERENCES CURRENCY(ID)
)
ENGINE=InnoDB;

CREATE TABLE BUSINESS_UNIT ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  COUNTRY_ID			INT(11) NOT NULL,
	  CODE      			VARCHAR(3) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  DESCRIPTION        	VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)
)
ENGINE=InnoDB;

CREATE TABLE LIMIT_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX LIMIT_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

/* Gold, Silver */
CREATE TABLE CUSTOMER_CLASSIFICATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_CLASSIFICATION_IX1 (CODE(35))
)
ENGINE=InnoDB;

/* Personal, Organization*/
CREATE TABLE CUSTOMER_CATEGORY (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_CATEGORY_IX1 (CODE(35))
)
ENGINE=InnoDB;

/* Student, Business Owner*/
CREATE TABLE CUSTOMER_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_CAT_ID	 			INT(11) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_TYPE_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_CAT_ID) REFERENCES CUSTOMER_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_TY_ID				INT (11) NOT NULL,
	  CUST_CLASS_ID				INT (11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  PIN 						VARCHAR(4) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  PRIMARY_EMAIL 			VARCHAR(50) NOT NULL,
	  SECONDARY_EMAIL 			VARCHAR(50) NULL,
	  PRIMARY_MOBILE 			VARCHAR(35) NOT NULL,
	  SECONDARY_MOBILE 			VARCHAR(35) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_TY_ID) REFERENCES CUSTOMER_TYPE (ID),
	  FOREIGN KEY (CUST_CLASS_ID) REFERENCES CUSTOMER_CLASSIFICATION (ID)
)
ENGINE=InnoDB;

/* Current account, Savings account*/
CREATE TABLE ACCOUNT_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  ACCOUNT_NO_FORMAT			VARCHAR(15) NULL,
	  CHEQUE_NO_FORMAT			VARCHAR(15) NULL,
	  CARD_NO_FORMAT			VARCHAR(15) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX ACCOUNT_TYPE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE ACCOUNT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CURRENCY_ID				INT(11) NOT NULL,
	  ACCOUNT_TY_ID				INT(11) NOT NULL,
	  CODE    					VARCHAR(75) NOT NULL,
	  NAME    					VARCHAR(150) NOT NULL,
	  ACCOUNT_NO    			VARCHAR(35) NOT NULL,
	  IS_JOINT_FG				CHAR(1) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX ACCOUNT_IX1 (CODE(35)),
	  FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (ID),
	  FOREIGN KEY (ACCOUNT_TY_ID) REFERENCES ACCOUNT_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_ACCOUNT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_ID					INT(11) NOT NULL,
	  ACCOUNT_ID				INT(11) NOT NULL,
	  CODE    					VARCHAR(75) NOT NULL,
	  NAME    					VARCHAR(150) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  IS_DEFAULT_FG				CHAR(1) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_ACCOUNT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_BLACKLIST (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_ID					INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID),
	  UNIQUE INDEX CUSTOMER_BLACKLIST_IX1 (CODE(35))
)
ENGINE=InnoDB;

/* SMS, Email, IM, File, DB etc*/
CREATE TABLE DATA_CHANNEL_CATEGORY (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_CHANNEl_CATEGORY_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_CHANNEL_CATEGORY_IX2 (CODE(75))
)
ENGINE=InnoDB;

CREATE TABLE DATA_CHANNEL_ADAPTER (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_CHANNEL_ADAPTER_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_CHANNEL_ADAPTER_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* SMS (SMPP) Gateway, SMS (HTTP) Gateway, Email POP Gateway, EMAIL (SMTP) Gateway, IM Gateway etc*/
CREATE TABLE DATA_CHANNEL_TYPE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CATEGORY_ID			INT (11) NOT NULL,
	  ADAPTER_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_CHANNEL_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_CHANNEL_TYPE_IX2 (CODE(35)),
	  FOREIGN KEY (ADAPTER_ID) REFERENCES DATA_CHANNEL_ADAPTER (ID),
	  FOREIGN KEY (CATEGORY_ID) REFERENCES DATA_CHANNEL_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_CHANNEL_STATUS (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_CHANNEL_STATUS_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_CHANNEL_STATUS_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_CHANNEL (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CHANNEL_TY_ID			INT (11) NOT NULL,
	  CHANNEL_STATUS_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  IP_ADDR 				VARCHAR(75) NULL,
	  PORT_NO 				INT (11) NULL,
	  URL					VARCHAR(150) NULL,
	  DS_DB 				VARCHAR(75) NULL,
	  DS_TBL_NM				VARCHAR(75) NULL,
	  USERNAME				VARCHAR(35) NULL,
	  PASSWORD				VARCHAR(35) NULL,
	  INBOUND_OUTBOUND_CD   VARCHAR(15) NOT NULL,
	  CONN_SECURITY_CD	    VARCHAR(15) NOT NULL,
	  AUTH_METHOD_CD	    VARCHAR(15) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_CHANNEL_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_CHANNEL_IX2 (CODE(35)),
	  FOREIGN KEY (CHANNEL_TY_ID) REFERENCES DATA_CHANNEL_TYPE (ID),
	  FOREIGN KEY (CHANNEL_STATUS_ID) REFERENCES DATA_CHANNEL_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION_CATEGORY (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TRANSACTION_CATEGORY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION_TYPE (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  TRANSACTION_CAT_ID	INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  MATCH_FG         		char(1) NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR     varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TRANSACTION_TY_IX1 (CODE(35)),
	  FOREIGN KEY (TRANSACTION_CAT_ID) REFERENCES SERVICE_TRANSACTION_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION_STATUS (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TRANSACTION_STATUS_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  TXN_TY_ID				INT(11) NOT NULL,
	  TXN_STATUS_ID			INT(11) NOT NULL,
	  CHANNEL_ID			INT(11) NOT NULL,
	  CURRENCY_ID			INT(11) NOT NULL,
	  ACCOUNT_ID			INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  AMOUNT				DECIMAL(38, 2) NOT NULL,
	  TXN_DATE				DATE NOT NULL,
	  CHEQUE_NO				VARCHAR(15) NULL,
	  CARD_NO				VARCHAR(15) NULL,
	  ACCOUNT_NM			VARCHAR(75) NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TXN_IX1 (CODE(35)),
	  FOREIGN KEY (CHANNEL_ID) REFERENCES DATA_CHANNEL (ID),
	  FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (ID),
	  FOREIGN KEY (ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNT (ID),
	  FOREIGN KEY (TXN_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID),
	  FOREIGN KEY (TXN_STATUS_ID) REFERENCES SERVICE_TRANSACTION_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUST_CAT_TXN_TYPE_NOTIFICATION_OPTIONS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_CAT_ID				INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  SMS_FG         			char(1) NOT NULL,
	  SMS_AMT					DECIMAL(32,2) NULL,
	  EMAIL_FG         			char(1) NOT NULL,
	  EMAIL_AMT					DECIMAL(32,2) NULL,
	  IVR_FG         			char(1) NOT NULL,
	  IVR_AMT					DECIMAL(32,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUST_CAT_TXN_TYPE_NOTIF_OPT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_CAT_ID) REFERENCES CUSTOMER_CATEGORY (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUST_TYPE_TXN_TYPE_NOTIFICATION_OPTIONS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_TY_ID				INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  SMS_FG         			char(1) NOT NULL,
	  SMS_AMT					DECIMAL(32,2) NULL,
	  EMAIL_FG         			char(1) NOT NULL,
	  EMAIL_AMT					DECIMAL(32,2) NULL,
	  IVR_FG         			char(1) NOT NULL,
	  IVR_AMT					DECIMAL(32,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUST_TYPE_TXN_TYPE_NOTIF_OPT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_TY_ID) REFERENCES CUSTOMER_TYPE (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUST_TXN_TYPE_NOTIFICATION_OPTIONS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_ID					INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  SMS_FG         			char(1) NOT NULL,
	  SMS_AMT					DECIMAL(32,2) NULL,
	  EMAIL_FG         			char(1) NOT NULL,
	  EMAIL_AMT					DECIMAL(32,2) NULL,
	  IVR_FG         			char(1) NOT NULL,
	  IVR_AMT					DECIMAL(32,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUST_TXN_TYPE_NOTIF_OPT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUST_CAT_TXN_TYPE_CONFIRMATION_OPTIONS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_CAT_ID				INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  SMS_FG         			char(1) NOT NULL,
	  SMS_AMT					DECIMAL(32,2) NULL,
	  EMAIL_FG         			char(1) NOT NULL,
	  EMAIL_AMT					DECIMAL(32,2) NULL,
	  IVR_FG         			char(1) NOT NULL,
	  IVR_AMT					DECIMAL(32,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUST_CAT_TXN_TYPE_CONF_OPT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_CAT_ID) REFERENCES CUSTOMER_CATEGORY (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUST_TYPE_TXN_TYPE_CONFIRMATION_OPTIONS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_TY_ID				INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  SMS_FG         			char(1) NOT NULL,
	  SMS_AMT					DECIMAL(32,2) NULL,
	  EMAIL_FG         			char(1) NOT NULL,
	  EMAIL_AMT					DECIMAL(32,2) NULL,
	  IVR_FG         			char(1) NOT NULL,
	  IVR_AMT					DECIMAL(32,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUST_TYPE_TXN_TYPE_CONF_OPT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_TY_ID) REFERENCES CUSTOMER_TYPE (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUST_TXN_TYPE_CONFIRMATION_OPTIONS (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_ID					INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  SMS_FG         			char(1) NOT NULL,
	  SMS_AMT					DECIMAL(32,2) NULL,
	  EMAIL_FG         			char(1) NOT NULL,
	  EMAIL_AMT					DECIMAL(32,2) NULL,
	  IVR_FG         			char(1) NOT NULL,
	  IVR_AMT					DECIMAL(32,2) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUST_TXN_TYPE_CONF_OPT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE TXN_NOTIFICATION_STATUS (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TXN_NOTIFICATION_STATUS (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE TXN_CONFIRMATION_STATUS (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TXN_CONFIRMATION_STATUS (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE TXN_AWAITING_NOTIFICATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  TRANSACTION_ID			INT (11) NOT NULL,
	  NOTIFICATION_TY_ID		INT (11) NOT NULL,
	  STATUS_ID					INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX TXN_AWAITING_NOTIFICATION_IX1 (CODE(35)),
	  FOREIGN KEY (TRANSACTION_ID) REFERENCES SERVICE_TRANSACTION (ID),
	  FOREIGN KEY (NOTIFICATION_TY_ID) REFERENCES NOTITFICATION_TYPE (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES TXN_NOTIFICATION_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE TXN_AWAITING_CONFIRMATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  TRANSACTION_ID			INT (11) NOT NULL,
	  NOTIFICATION_TY_ID		INT (11) NOT NULL,
	  STATUS_ID					INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX TXN_AWAITING_CONFIRMATION_IX1 (CODE(35)),
	  FOREIGN KEY (TRANSACTION_ID) REFERENCES SERVICE_TRANSACTION (ID),
	  FOREIGN KEY (NOTIFICATION_TY_ID) REFERENCES NOTITFICATION_TYPE (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES TXN_CONFIRMATION_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_CLASSIFICATION_TRANSACTION_LIMIT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_CLASS_ID				INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  LIMIT_TY_ID				INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  AMOUNT					DECIMAL(32,2) NOT NULL,
	  START_DT        			DATE NOT NULL,
	  END_DT        			DATE NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_LIMIT_IX1 (CODE(35)),
	  FOREIGN KEY (LIMIT_TY_ID) REFERENCES LIMIT_TYPE (ID),
	  FOREIGN KEY (CUST_CLASS_ID) REFERENCES CUSTOMER_CLASSIFICATION (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_CATEGORY_TRANSACTION_LIMIT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_CAT_ID				INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  LIMIT_TY_ID				INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  AMOUNT					DECIMAL(32,2) NOT NULL,
	  START_DT        			DATE NOT NULL,
	  END_DT        			DATE NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_LIMIT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_CAT_ID) REFERENCES CUSTOMER_CATEGORY (ID),
	  FOREIGN KEY (LIMIT_TY_ID) REFERENCES LIMIT_TYPE (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_TYPE_TRANSACTION_LIMIT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_TY_ID				INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  LIMIT_TY_ID				INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  AMOUNT					DECIMAL(32,2) NOT NULL,
	  START_DT        			DATE NOT NULL,
	  END_DT        			DATE NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_LIMIT_IX1 (CODE(35)),
	  FOREIGN KEY (LIMIT_TY_ID) REFERENCES LIMIT_TYPE (ID),
	  FOREIGN KEY (CUST_TY_ID) REFERENCES CUSTOMER_TYPE (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_TRANSACTION_LIMIT (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_ID					INT (11) NOT NULL,
	  TRANSACTION_TY_ID			INT (11) NOT NULL,
	  LIMIT_TY_ID				INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT NULL,
	  NAME						VARCHAR(75) NOT NULL,
	  AMOUNT					DECIMAL(32,2) NOT NULL,
	  START_DT        			DATE NOT NULL,
	  END_DT        			DATE NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX CUSTOMER_LIMIT_IX1 (CODE(35)),
	  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (LIMIT_TY_ID) REFERENCES LIMIT_TYPE (ID),
	  FOREIGN KEY (TRANSACTION_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

/* Error, Success */
CREATE TABLE TEMPLATE_CLASSIFICATION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TEMPLATE_CLASSIFICATION_IX1 (NAME(75)),
	  UNIQUE INDEX TEMPLATE_CLASSIFICATION_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* Customer,  User etc */
CREATE TABLE TEMPLATE_CATEGORY (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TEMPLATE_CATEGORY_IX1 (NAME(75)),
	  UNIQUE INDEX TEMPLATE_CATEGORY_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* Transaction, Advices etc */
CREATE TABLE TEMPLATE_TYPE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  TEMPLATE_CAT_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TEMPLATE_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX TEMPLATE_TYPE_IX2 (CODE(35)),
	  FOREIGN KEY (TEMPLATE_CAT_ID) REFERENCES TEMPLATE_CATEGORY (ID)
)
ENGINE=InnoDB;

/* */
CREATE TABLE TEMPLATE_TYPE_TAG (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  TEMPLATE_TY_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  TAG_VAL 				VARCHAR(75) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TEMPLATE_TYPE_TAG_IX1 (NAME(75)),
	  UNIQUE INDEX TEMPLATE_TYPE_TAG_IX2 (CODE(35)),
	  FOREIGN KEY (TEMPLATE_TY_ID) REFERENCES TEMPLATE_TYPE (ID)
)
ENGINE=InnoDB;

/* */
CREATE TABLE TEMPLATE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  TEMPLATE_TY_ID		INT (11) NOT NULL,
	  TEMPLATE_CLASS_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  SUBJECT_TXT 			VARCHAR(255) NOT NULL,
	  MESSAGE_TXT 			TEXT NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TEMPLATE_IX1 (NAME(75)),
	  UNIQUE INDEX TEMPLATE_IX2 (CODE(35)),
	  FOREIGN KEY (TEMPLATE_TY_ID) REFERENCES TEMPLATE_TYPE (ID),
	  FOREIGN KEY (TEMPLATE_CLASS_ID) REFERENCES TEMPLATE_CLASSIFICATION (ID)
)
ENGINE=InnoDB;

/* User, Customer, System */
CREATE TABLE NOTIFICATION_CATEGORY (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX NOTIFICATION_CATEGORY_IX1 (NAME(75)),
	  UNIQUE INDEX NOTIFICATION_CATEGORY_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* Transaction matched, Transaction not matched, etc*/
CREATE TABLE NOTIFICATION_TYPE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  NOTIFICATION_CAT_ID	INT (11) NOT NULL,
	  TEMPLATE_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  AUTO_RESP_FG     		CHAR(1) NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX NOTIFICATION_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX NOTIFICATION_TYPE_IX2 (CODE(35)),
	  FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATE (ID),
	  FOREIGN KEY (NOTIFICATION_CAT_ID) REFERENCES NOTIFICATION_CATEGORY (ID)
)
ENGINE=InnoDB;

/* */
CREATE TABLE CUSTOMER_NOTIFICATION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CUSTOMER_ID			INT (11) NOT NULL,
	  NOTIFICATION_TY_ID	INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CUSTOMER_NOTIFICATION_IX2 (CODE(35)),
	  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (NOTIFICATION_TY_ID) REFERENCES NOTIFICATION_TYPE (ID)
)
ENGINE=InnoDB;

/* Channels to use when notifying customers */
CREATE TABLE CUSTOMER_CLASSIFICATION_NOTIFICATION_CHANNEL (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CUST_CLASS_ID			INT (11) NOT NULL,
	  CHANNEL_CAT_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CUSTOMER_CLASSIFICATION_NOTIFICATION_CHANNEL_IX2 (CODE(35)),
	  FOREIGN KEY (CHANNEL_CAT_ID) REFERENCES DATA_CHANNEL_CATEGORY (ID),
	  FOREIGN KEY (CUST_CLASS_ID) REFERENCES CUSTOMER_CLASSIFICATION (ID)
)
ENGINE=InnoDB;

/* Channels to use when notifying customers */
CREATE TABLE CUSTOMER_CATEGORY_NOTIFICATION_CHANNEL (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CUST_CAT_ID			INT (11) NOT NULL,
	  CHANNEL_CAT_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CUSTOMER_CATEGORY_NOTIFICATION_CHANNEL_IX2 (CODE(35)),
	  FOREIGN KEY (CUST_CAT_ID) REFERENCES CUSTOMER_CATEGORY (ID),
	  FOREIGN KEY (CHANNEL_CAT_ID) REFERENCES DATA_CHANNEL_CATEGORY (ID)
)
ENGINE=InnoDB;

/* Channels to use when notifying customers */
CREATE TABLE CUSTOMER_TYPE_NOTIFICATION_CHANNEL (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CUST_TY_ID			INT (11) NOT NULL,
	  CHANNEL_CAT_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CUSTOMER_TYPE_NOTIFICATION_CHANNEL_IX2 (CODE(35)),
	  FOREIGN KEY (CUST_TY_ID) REFERENCES CUSTOMER_TYPE (ID),
	  FOREIGN KEY (CHANNEL_CAT_ID) REFERENCES DATA_CHANNEL_CATEGORY (ID)
)
ENGINE=InnoDB;

/* Channels to use when notifying customers */
CREATE TABLE CUSTOMER_NOTIFICATION_CHANNEL (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CUST_ID				INT (11) NOT NULL,
	  CHANNEL_CAT_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CUSTOMER_NOTIFICATION_CHANNEL_IX2 (CODE(35)),
	  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (CHANNEL_CAT_ID) REFERENCES DATA_CHANNEL_CATEGORY (ID)
)
ENGINE=InnoDB;

/* SMS, Email, IM etc*/
CREATE TABLE MESSAGE_CATEGORY (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_CATEGORY_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_CATEGORY_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* SMS_SMPP, SMS_HTTP, Email_SMTP_POP, Email_SMTP_IMAP etc*/
CREATE TABLE MESSAGE_TYPE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  MSG_CAT_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  AUTO_RESP_FG     		CHAR(1) NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_TYPE_IX2 (CODE(35)),
	  FOREIGN KEY (MSG_CAT_ID) REFERENCES MESSAGE_CATEGORY (ID)
)
ENGINE=InnoDB;

/* Received, Sent and Not Sent*/
CREATE TABLE MESSAGE_STATUS (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_STATUS_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_STATUS_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* Inbound, Outbound and Internal */
CREATE TABLE MESSAGE_CLASSIFICATION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_CLASSIFICATION_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_CLASSIFICATION_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* Advice, Transaction etc*/
CREATE TABLE MESSAGE_APPLICATION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_APPLICATION_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_APPLICATION_IX2 (CODE(35))
)
ENGINE=InnoDB;

/* Advice, Transact */
CREATE TABLE MESSAGE_APPLICATION_TAG (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  MSG_APPL_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  TAG_VAL 				VARCHAR(75) NOT NULL,
	  IS_REGEX_FG         	char(1) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_APPLICATION_TAG_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_APPLICATION_TAG_IX2 (CODE(35)),
	  FOREIGN KEY (MSG_APPL_ID) REFERENCES MESSAGE_APPLICATION (ID)
)
ENGINE=InnoDB;

/* Advice Request, Advice Inquiry etc*/
CREATE TABLE MESSAGE_APPLICATION_ACTION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  MSG_APPL_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  AUTO_RESP_FG     		CHAR(1) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_APPLICATION_ACTION_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_APPLICATION_ACTION_IX2 (CODE(35)),
	  FOREIGN KEY (MSG_APPL_ID) REFERENCES MESSAGE_APPLICATION (ID)
)
ENGINE=InnoDB;

/* PAY, CHEQUE, INQUIRY */
CREATE TABLE MESSAGE_APPLICATION_ACTION_TAG (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  ACTION_ID				INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  TAG_VAL 				VARCHAR(75) NOT NULL,
	  IS_REGEX_FG         	char(1) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_APPLICATION_ACTION_TAG_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_APPLICATION_ACTION_TAG_IX2 (CODE(35)),
	  FOREIGN KEY (ACTION_ID) REFERENCES MESSAGE_APPLICATION_ACTION (ID)
)
ENGINE=InnoDB;

/* */
CREATE TABLE MESSAGE_APPLICATION_NOTIFICATION_MAP (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  NOTIFICATION_TY_ID	INT (11) NOT NULL,
	  MSG_APPL_ACTION_ID	INT (11) NOT NULL,
	  CODE 					VARCHAR(150) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  TAG_VAL 				VARCHAR(75) NOT NULL,
	  IS_REGEX_FG         	char(1) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_APPLICATION_NOTIFICATION_MAP_IX1 (NAME(150)),
	  UNIQUE INDEX MESSAGE_APPLICATION_NOTIFICATION_MAP_IX2 (CODE(150)),
	  FOREIGN KEY (NOTIFICATION_TY_ID) REFERENCES NOTIFICATION_TYPE (ID),
	  FOREIGN KEY (MSG_APPL_ACTION_ID) REFERENCES MESSAGE_APPLICATION_ACTION (ID)
)
ENGINE=InnoDB;

/* Message */
CREATE TABLE MESSAGE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  MSG_APPL_ID				INT (11) NOT NULL,
	  MSG_TY_ID				INT (11) NOT NULL,
	  MSG_CLASS_ID			INT (11) NOT NULL,
	  MSG_STATUS_ID		 	INT (11) NOT NULL,
	  CHANNEL_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(150) NOT NULL,
	  MESSAGE_FROM 			VARCHAR(75) NOT NULL,
	  MESSAGE_TO 			VARCHAR(75) NOT NULL,
	  MESSAGE_SUBJECT 		VARCHAR(100) NULL,
	  MESSAGE_TXT			VARCHAR(255) NOT NULL,
	  MSG_ATTACHMENT_TY		VARCHAR(150) NULL,
	  MSG_ATTACHMENT_FILE	VARCHAR(255) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_IX2 (CODE(150)),
	  FOREIGN KEY (MSG_TY_ID) REFERENCES MESSAGE_TYPE (ID),
	  FOREIGN KEY (MSG_APPL_ID) REFERENCES MESSAGE_APPLICATION (ID),
	  FOREIGN KEY (MSG_STATUS_ID) REFERENCES MESSAGE_STATUS (ID),
	  FOREIGN KEY (CHANNEL_ID) REFERENCES DATA_CHANNEL (ID),
	  FOREIGN KEY (MSG_CLASS_ID) REFERENCES MESSAGE_CLASSIFICATION (ID)
)
ENGINE=InnoDB;

CREATE TABLE MESSAGE_ATTACHMENT (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  MSG_ID				INT (11) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  DATA_TY 				VARCHAR(15) NOT NULL,
	  DATA_URL 				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_ATTACHMENT_IX2 (CODE(35)),
	  FOREIGN KEY (MSG_ID) REFERENCES MESSAGE (ID)
)
ENGINE=InnoDB;

CREATE TABLE MESSAGE_ACTION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  MSG_ID				INT (11) NOT NULL,
	  MSG_APPL_ACTION_ID	INT (11) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_ACTION_IX1 (CODE(35)),
	  FOREIGN KEY (MSG_ID) REFERENCES MESSAGE (ID),
	  FOREIGN KEY (MSG_APPL_ACTION_ID) REFERENCES MESSAGE_APPLICATION_ACTION (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_MESSAGE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  MSG_ID				INT (11) NOT NULL,
	  CUSTOMER_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX CUSTOMER_MESSAGE_IX2 (CODE(35)),
	  FOREIGN KEY (MSG_ID) REFERENCES MESSAGE (ID),
	  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_REQUEST_MESSAGE_STATUS (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_REQUEST_MESSAGE_STATUS_IX1 (CODE(35))
)
ENGINE=InnoDB;

/* Data input job code is a code and not an id because it can be null, 
 * hence a code is used to avoid problems noticed when handling nullable ids */
CREATE TABLE ADVICE_REQUEST_MESSAGE (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CHANNEL_ID			INT(11) NOT NULL,
	  CUSTOMER_ID			INT(11) NOT NULL,
	  STATUS_ID				INT(11) NOT NULL,
	  INPUT_JOB_CD			VARCHAR(35) NULL,
	  SOURCE_ADDRESS		VARCHAR(75) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  AMOUNT				DECIMAL(32,2) NOT NULL,
	  ACCOUNT_NO			VARCHAR(35) NOT NULL,
	  CHEQUE_NO				VARCHAR(35) NULL,
	  CARD_NO				VARCHAR(15) NULL,
	  CURRENCY_CD			VARCHAR(15) NOT NULL,
	  ADVICE_TY_TXT			VARCHAR(75) NOT NULL,
	  ADVICE_TXT		    TEXT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_REQUEST_MESSAGE_IX1 (CODE(75)),
	  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (CHANNEL_ID) REFERENCES DATA_CHANNEL (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES ADVICE_REQUEST_MESSAGE_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_CLASSIFICATION (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_CLASSIFICATION_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_TYPE (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  TXN_TY_ID				INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  REQ_FEEDBACK			CHAR(1) NULL,
	  FEEDBACK_MSG			VARCHAR(255) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_TY_IX1 (CODE(35)),
	  FOREIGN KEY (TXN_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_TYPE_TAG (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  ADVICE_TY_ID 			INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  ADVICE_TY_TAG_VAL 	TEXT NOT NULL,
	  IS_REGEX_FG         	char(1) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_TY_TAG_IX1 (CODE(35)),
	  FOREIGN KEY (ADVICE_TY_ID) REFERENCES ADVICE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_STATUS (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_ST_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE ADVICE (
	  ID				 		INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  ADVICE_CLASS_ID			INT (11) NOT NULL,
	  ADVICE_REQUEST_ID			INT (11) NOT NULL,
	  ADVICE_TY_ID				INT (11) NOT NULL,
	  ADVICE_ST_ID				INT (11) NOT NULL,
	  CUSTOMER_ID				INT (11) NOT NULL,
	  ACCOUNT_ID				INT (11) NOT NULL,
	  CURRENCY_ID				INT (11) NOT NULL,
	  ADVICE_TXT		    	TEXT NULL,
	  CARD_NO				    VARCHAR(35) NULL,
	  CHEQUE_NO					VARCHAR(35) NULL,
	  ACCOUNT_NM				VARCHAR(75) NULL,
	  AMOUNT 					DECIMAL(38,2) NOT NULL,
	  START_DT        			DATE NULL,
	  END_DT        			DATE NULL,
	  MAX_MATCHES				INT(11) NOT NULL,
	  MATCH_COUNT				INT(11) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCY (ID),
	  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
	  FOREIGN KEY (ADVICE_TY_ID) REFERENCES ADVICE_TYPE (ID),
	  FOREIGN KEY (ADVICE_ST_ID) REFERENCES ADVICE_STATUS (ID),
	  FOREIGN KEY (ACCOUNT_ID) REFERENCES CUSTOMER_ACCOUNT (ID),
	  FOREIGN KEY (ADVICE_CLASS_ID) REFERENCES ADVICE_CLASSIFICATION (ID),
	  FOREIGN KEY (ADVICE_REQUEST_ID) REFERENCES ADVICE_REQUEST_MESSAGE (ID),
	  UNIQUE INDEX ADVICE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE ADVICED_TRANSACTION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  TXN_ID				INT (11)  NOT NULL,
	  ADVICE_ID				INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICED_TRANSACTION_IX1 (NAME(75)),
	  UNIQUE INDEX ADVICED_TRANSACTION_IX2 (CODE(35)),
	  FOREIGN KEY (ADVICE_ID) REFERENCES ADVICE (ID),
	  FOREIGN KEY (TXN_ID) REFERENCES SERVICE_TRANSACTION (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_EXTRACTOR (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_TYPE_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_PROCESSOR (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_PROCESSOR_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_PROCESSOR_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_LOADER (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_LOADER_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_LOADER_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_TRANSFORMER (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_TRANSFORMER_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_TRANSFORMER_IX2 (CODE(75))
)
ENGINE=InnoDB;

CREATE TABLE DATA_STRUCTURE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  DS_STRUCT_DELIMETER 	CHAR(1) NULL,
	  SKIP_FIRST_FG			CHAR(1) NULL,
	  STRICT_FG				CHAR(1) NULL,
	  TARGET_PRI_ENTITY_CD	VARCHAR(75) NOT NULL,
	  TARGET_SEC_ENTITY_CD	VARCHAR(75) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_STRUCTURE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_STRUCTURE_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_FIELD_TYPE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_FIELD_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_FIELD_TYPE_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_FIELD (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  DATA_TRANSFORMER_ID	INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  DATA_STRUCT_ID	 	INT (11) NOT NULL,
	  DATA_FIELD_TY_ID 		INT (11) NOT NULL,
	  TARGET_ENTITY_CD		VARCHAR(75) NOT NULL,
	  TARGET_ENTITY_FIELD	VARCHAR(75) NOT NULL,
	  REL_TARGET_ENTITY_CD	VARCHAR(75) NULL,
	  FIELD_FORMAT			VARCHAR(75) NULL,
	  REQUIRED_FG			CHAR (1) NOT NULL,
	  SEQ_NO				INT(11) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_FIELD_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_FIELD_IX2 (CODE(35)),
	  FOREIGN KEY (DATA_STRUCT_ID) REFERENCES DATA_STRUCTURE (ID),
	  FOREIGN KEY (DATA_FIELD_TY_ID) REFERENCES DATA_FIELD_TYPE (ID),
	  FOREIGN KEY (DATA_TRANSFORMER_ID) REFERENCES DATA_TRANSFORMER (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_TYPE (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_TYPE_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CHANNEL_ID			INT (11) NOT NULL,
	  DATA_TY_ID			INT (11) NOT NULL,
	  DATA_STRUCT_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_IX2 (CODE(75)),
	  FOREIGN KEY (CHANNEL_ID) REFERENCES DATA_CHANNEL (ID),
	  FOREIGN KEY (DATA_TY_ID) REFERENCES DATA_TYPE (ID),
	  FOREIGN KEY (DATA_STRUCT_ID) REFERENCES DATA_STRUCTURE (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  DATA_ID				INT (11) NOT NULL,
	  DATA_LOADER_ID 		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_IX2 (CODE(35)),
	  FOREIGN KEY (DATA_ID) REFERENCES DATA (ID),
	  FOREIGN KEY (DATA_LOADER_ID) REFERENCES DATA_LOADER (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_PROCESSORS (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  DATA_INPUT_ID  		INT (11) NOT NULL,
	  DATA_PROCESSOR_ID  	INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_PROCESSORS_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_PROCESSORS_IX2 (CODE(35)),
	  FOREIGN KEY (DATA_INPUT_ID) REFERENCES DATA_INPUT (ID),
	  FOREIGN KEY (DATA_PROCESSOR_ID) REFERENCES DATA_PROCESSOR (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_JOB_TYPE (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_JOB_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_JOB_TYPE_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_JOB_STATUS (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_JOB_STATUS_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_JOB_STATUS_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_JOB (
	  ID 						INT (11) AUTO_INCREMENT NOT NULL,
	  DATA_INPUT_ID 			INT(11) NOT NULL,
	  DATA_INPUT_JOB_TY_ID 		INT(11) NOT NULL,
	  DATA_INPUT_JOB_STATUS_ID 	INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  DI_FREQ_VAL				INT(11) NOT NULL,
	  DI_FREQ_CD				VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   			DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     	VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_JOB_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_JOB_IX2 (CODE(35)),
	  FOREIGN KEY (DATA_INPUT_ID) REFERENCES DATA_INPUT (ID),
	  FOREIGN KEY (DATA_INPUT_JOB_TY_ID) REFERENCES DATA_INPUT_JOB_TYPE (ID),
	  FOREIGN KEY (DATA_INPUT_JOB_STATUS_ID) REFERENCES DATA_INPUT_JOB_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE TABLE_DATA (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  JOB_ID				INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  PRIM_ENTITY			INT(11) NOT NULL,
	  PRIM_REC_READ			INT(11) NOT NULL,
	  PRIM_REC_CREATED		INT(11) NOT NULL,
	  PRIM_REC_REJECTED		INT(11) NOT NULL,
	  SEC_ENTITY			INT(11) NULL,
	  SEC_REC_READ			INT(11) NULL,
	  SEC_REC_CREATED		INT(11) NULL,
	  SEC_REC_REJECTED		INT(11) NULL,
	  TOT_REC_READ			INT(11) NOT NULL,
	  TOT_REC_CREATED		INT(11) NOT NULL,
	  TOT_REC_REJECTED		INT(11) NOT NULL,
	  IMPORT_STATUS_FG  	CHAR(1) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX TABLE_DATA_IX1 (NAME(75)),
	  UNIQUE INDEX TABLE_DATA_IX2 (CODE(35)),
	  FOREIGN KEY (JOB_ID) REFERENCES DATA_INPUT_JOB (ID)
)
ENGINE=InnoDB;

CREATE TABLE ROW_DATA (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  TABLE_DATA_ID		 	INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  IS_HEADER_FG		  	CHAR(1) NOT NULL,
	  IMPORT_STATUS_FG  	CHAR(1) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ROW_DATA_IX1 (NAME(75)),
	  UNIQUE INDEX ROW_DATA_IX2 (CODE(35)),
	  FOREIGN KEY (TABLE_DATA_ID) REFERENCES TABLE_DATA (ID)
)
ENGINE=InnoDB;

CREATE TABLE CELL_DATA (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  ROW_DATA_ID 			INT(11) NOT NULL,
	  DATA_FIELD_ID			INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  CELL_DATA				TEXT NOT NULL,
	  IMPORT_STATUS_FG  	CHAR(1) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ROW_DATA_IX1 (NAME(75)),
	  UNIQUE INDEX ROW_DATA_IX2 (CODE(35)),
	  FOREIGN KEY (ROW_DATA_ID) REFERENCES ROW_DATA (ID),
	  FOREIGN KEY (DATA_FIELD_ID) REFERENCES DATA_FIELD (ID)
)
ENGINE=InnoDB;


CREATE TABLE DATA_INPUT_JOB_SUMMARY_STATUS (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_JOB_SUMMARY_STATUS_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_JOB_SUMMARY_STATUS_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_JOB_SUMMARY (
	  ID 								INT (11) AUTO_INCREMENT NOT NULL,
	  JOB_ID 							INT(11) NOT NULL,
	  STATUS_ID 						INT(11) NOT NULL,
	  CODE 								VARCHAR(75) NOT NULL,
	  RECORDS_READ						INT(11) NOT NULL,
	  RECORDS_REJECTED					INT(11) NOT NULL,
	  RECORDS_READ_PERCENTAGE			INT(11) NOT NULL,
	  PRIM_ENTITY_NAME					VARCHAR(150) NOT NULL,
	  PRIM_ENTITY_RECORDS_CREATED		INT(11) NOT NULL,
	  PRIM_ENTITY_RECORDS_REJECTED 		INT(11) NOT NULL,
	  PRIM_ENTITY_INPUT_PERCENATGE  	INT(11) NOT NULL,
	  SEC_ENTITY_NAME					VARCHAR(150) NULL,
	  SEC_ENTITY_RECORDS_CREATED		INT(11) NULL,
	  SEC_ENTITY_RECORDS_REJECTED  		INT(11) NULL,
	  SEC_ENTITY_INPUT_PERCENATGE  		INT(11) NULL,
	  TOTAL_ENTITIES_CREATED 			INT(11) NOT NULL,
	  TOTAL_ENTITIES_REJECTED 			INT(11) NOT NULL,
	  TOTAL_ENTITIES_INPUT_PERCENTAGE	INT(11) NOT NULL,
	  TXNS_MATCHED						INT(11) NULL,
	  TXNS_UNMATCHED					INT(11) NULL,
	  TXN_MATCH_PERCENTAGE				VARCHAR(3) NULL,
	  EFFECTIVE_DT   					DATE NOT NULL,
	  REC_ST         					CHAR(1) NOT NULL,
	  VERSION_NO     					INT(11) NULL,
	  ROW_TS         					TIMESTAMP  NULL,
	  CREATED_DT        				DATE NOT NULL,
	  CREATED_BY_USR  	 				VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 					TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     			VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_JOB_SUMMARY_IX2 (CODE(75)),
	  FOREIGN KEY (JOB_ID) REFERENCES DATA_INPUT_JOB (ID),
	  FOREIGN KEY (STATUS_ID) REFERENCES DATA_INPUT_JOB_SUMMARY_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_JOB_RECORDS_SUMMARY_STATUS (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_JOB_SUMMARY_STATUS_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_JOB_SUMMARY_STATUS_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_JOB_RECORDS_SUMMARY (
	  ID 							INT(11) AUTO_INCREMENT NOT NULL,
	  JOB_SUMMARY_ID 				INT(11) NOT NULL,
	  RECORD_SUMMARY_STATUS_ID		INT(11) NOT NULL,
	  CODE 							VARCHAR(75) NOT NULL,
	  RECORD_NUMBER					INT(11) NOT NULL,
	  RECORD_DATA					LONGBLOB NOT NULL,
	  PRIMARY_ENTITY_NAME			VARCHAR(75) NOT NULL,
	  PRIMARY_ENTITY_ID				INT(11) NOT NULL,
	  PRIMARY_ENTITY_STATUS			VARCHAR(35) NOT NULL,
	  PRIMARY_ENTITY_STATUS_DESC	VARCHAR(150) NOT NULL,
	  SECONDARY_ENTITY_NAME			VARCHAR(75) NULL,
	  SECONDARY_ENTITY_ID			INT(11) NULL,
	  SECONDARY_ENTITY_STATUS		VARCHAR(35) NULL,
	  SECONDARY_ENTITY_STATUS_DESC	VARCHAR(150) NULL,
	  EFFECTIVE_DT   				DATE NOT NULL,
	  REC_ST         				CHAR(1) NOT NULL,
	  VERSION_NO     				INT(11) NULL,
	  ROW_TS         				TIMESTAMP  NULL,
	  CREATED_DT        			DATE NOT NULL,
	  CREATED_BY_USR  	 			VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 				TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     		VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (JOB_SUMMARY_ID) REFERENCES DATA_INPUT_JOB_SUMMARY (ID),
	  FOREIGN KEY (RECORD_SUMMARY_STATUS_ID) REFERENCES DATA_INPUT_JOB_RECORDS_SUMMARY_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_MODULE (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  SEQUENCE_NO 			INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(50) NOT NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  DISPLAY_FG 			CHAR (1)  NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX APPLICATION_MODULE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  DISPLAY_NM 			VARCHAR(75) NOT NULL,
	  DISPLAY_NM_PLURAL		VARCHAR(75) NOT NULL,
	  HAS_TABLE				CHAR(1) NOT NULL,
	  DB_NAME				CHAR(50) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  UNIQUE INDEX APPLICATION_ENTITY_U01 (CODE(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY_FIELD_TYPE
(
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY_FIELD
(
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  FIELD_TY_ID			INT(11) NOT NULL,
	  ENTITY_ID 			INT(11)  NOT NULL,
	  RELATED_ENTITY_ID		INT(11) NULL,
	  CODE 					VARCHAR(150) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  STORAGE				CHAR(35) NOT NULL,
	  PRIMARYKEY_FG			CHAR(1) NOT NULL,
	  REQUIRED_FG			CHAR(1) NOT NULL,
	  SEARCH_FIELD_FG		CHAR(1) NOT NULL,
	  UNIQUE_FG				CHAR(1) NULL,
	  RELATED_FG			CHAR(1) NULL,
	  SIZE					INT(11) NULL,
	  MAX_DIGITS			INT(11) NULL,
	  DECIMAL_PRECISION		INT(11) NULL,
	  SEQUENCE_NO			INT(11) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_IX1 (CODE(150)),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (RELATED_ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (FIELD_TY_ID) REFERENCES APPLICATION_ENTITY_FIELD_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_TYPE
(
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FORM_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_ENTITY_FORM_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  MODULE_ID				INT (11)  NOT NULL,
	  FORM_TY_ID			INT (11)  NOT NULL,
	  ENTITY_ID				INT (11) NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  DISPLAY_NM 			VARCHAR(75) NOT NULL,
	  DISPLAY_NM_PLURAL		VARCHAR(75) NOT NULL,
	  HAS_TABLE				CHAR(1) NOT NULL,
	  DB_NAME				CHAR(50) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (FORM_TY_ID) REFERENCES APPLICATION_FORM_TYPE (ID),
	  UNIQUE INDEX APPLICATION_FORM_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_FIELD_TYPE
(
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_FORM_FIELD_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_FORM_FIELD_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_FIELD
(
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  FIELD_TY_ID			INT(11) NOT NULL,
	  FORM_ID 				INT(11) NOT NULL,
	  ENTITY_FIELD_ID		INT(11) NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  PRIMARYKEY_FG			CHAR(1) NOT NULL,
	  REQUIRED_FG			CHAR(1) NOT NULL,
	  RELATED_FG			CHAR(1) NULL,
	  SIZE					INT(11) NULL,
	  MAX_DIGITS			INT(11) NULL,
	  DECIMAL_PRECISION		INT(11) NULL,
	  SEQUENCE_NO			INT(11) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_IX1 (CODE(75)),
	  FOREIGN KEY (FORM_ID) REFERENCES APPLICATION_FORM (ID),
	  FOREIGN KEY (FIELD_TY_ID) REFERENCES APPLICATION_FORM_FIELD_TYPE (ID),
	  FOREIGN KEY (ENTITY_FIELD_ID) REFERENCES APPLICATION_ENTITY_FIELD (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_GROUP_TYPE
(
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ACT_GRP_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_GROUP (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  PARENT_GRP_ID     	INT (11) NULL,
	  GRP_TY_ID				INT (11) NOT NULL,
	  CODE 					VARCHAR(50) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  GRP_URL			    VARCHAR(255) NOT NULL,
	  GRP_SEQ 				INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(75) NOT NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  DISPLAY_FG 			CHAR (1)  NOT NULL,
	  IS_PARENT         	CHAR(1) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (PARENT_GRP_ID) REFERENCES APPLICATION_ACTIVITY_GROUP (ID),
	  FOREIGN KEY (GRP_TY_ID) REFERENCES APPLICATION_ACTIVITY_GROUP_TYPE (ID),
	  UNIQUE INDEX APPLICATION_ACT_GRP_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_TYPE (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ACT_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY (
	  ID		 			INT (11) AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  GRP_ID 			    INT (11)  NOT NULL,
	  ACTIVITY_TY_ID		INT (11)  NOT NULL,
	  ENTITY_ID 			INT (11) NULL,
	  FORM_ID				INT (11) NULL,
	  CODE 					VARCHAR(75) NOT NULL,
	  NAME 					VARCHAR(150) NOT NULL,
	  DESCRIPTION			VARCHAR(100) NULL,
	  ACTIVITY_URL		    VARCHAR(255) NULL,
	  ACTIVITY_SEQ 			INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(75) NOT NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  OPERATION_CD 			VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	        DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (GRP_ID) REFERENCES APPLICATION_ACTIVITY_GROUP (ID),
	  FOREIGN KEY (FORM_ID) REFERENCES APPLICATION_FORM (ID),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (ACTIVITY_TY_ID) REFERENCES APPLICATION_ACTIVITY_TYPE (ID),
	  UNIQUE INDEX APPLICATION_ACTIVITY_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_RELATED_ACTIVITY (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  SRC_ACT_ID 			INT (11) NULL,
	  DST_ACT_ID 			INT (11) NULL,
	  CODE 					VARCHAR(150) NOT NULL,
	  NAME 					VARCHAR(75) NOT NULL,
	  DESCRIPTION 			VARCHAR(150) NOT NULL,
	  REL_ACT_SEQ 			INT (11)  NOT NULL DEFAULT 0,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (SRC_ACT_ID) REFERENCES APPLICATION_ACTIVITY (ID),
	  FOREIGN KEY (DST_ACT_ID) REFERENCES APPLICATION_ACTIVITY (ID),
	  UNIQUE INDEX RELATED_ACTIVITY_U01 (SRC_ACT_ID, DST_ACT_ID)
)
ENGINE=InnoDB;

CREATE TABLE TEMP_RELATED_ACTIVITY (
	  ID					INT (11) AUTO_INCREMENT NOT NULL,
	  SOURCE_ACTIVITY		VARCHAR(75) NOT NULL, 
	  DESTINATION_ACTIVITY	VARCHAR(75) NOT NULL, 
	  RELATIONSHIP_TY		VARCHAR(75) NOT NULL,
	  PRIMARY KEY (ID)
)
ENGINE=InnoDB;

CREATE TABLE SYSTEM_GROUP (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  UNIQUE INDEX SYSTEM_GROUP_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SYSTEM_USER (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  GROUP_ID	 				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  USERNAME 					VARCHAR(75) NOT NULL,
	  PASSWORD 					VARCHAR(75) NOT NULL,
	  EMAIL 					VARCHAR(50) NOT NULL,
	  MOBILE 					VARCHAR(35) NOT NULL,
	  LOCKED_FG 				VARCHAR(1) NOT NULL,
	  MULTI_LOGIN_FG 			VARCHAR(1) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (GROUP_ID) REFERENCES SYSTEM_GROUP (ID),
	  UNIQUE INDEX SYSTEM_USER_U01 (USERNAME(35)),
	  UNIQUE INDEX SYSTEM_USER_U02 (CODE(35))
)
ENGINE=InnoDB;

/* */
CREATE TABLE SYSTEM_USER_NOTIFICATION (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  SYSTEM_USER_ID			INT (11) NOT NULL,
	  NOTIFICATION_TY_ID	INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SYSTEM_USER_NOTIFICATION_IX1 (CODE(35)),
	  FOREIGN KEY (SYSTEM_USER_ID) REFERENCES SYSTEM_USER (ID),
	  FOREIGN KEY (NOTIFICATION_TY_ID) REFERENCES NOTIFICATION_TYPE (ID)
)
ENGINE=InnoDB;

/* Channels to use when notifying users */
CREATE TABLE SYSTEM_USER_NOTIFICATION_CHANNEL (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  SYSTEM_USER_ID		INT (11) NOT NULL,
	  CHANNEL_CAT_ID		INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SYSTEM_USER_NOTIFICATION_CHANNEL_IX2 (CODE(35)),
	  FOREIGN KEY (SYSTEM_USER_ID) REFERENCES SYSTEM_USER (ID),
	  FOREIGN KEY (CHANNEL_CAT_ID) REFERENCES DATA_CHANNEL_CATEGORY (ID)
)
ENGINE=InnoDB;

/* */
CREATE TABLE SYSTEM_USER_MESSAGE (
	  ID				 	INT (11) AUTO_INCREMENT NOT NULL,
	  SYSTEM_USER_ID		INT (11) NOT NULL,
	  MESSAGE_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SYSTEM_USER_MESSAGE_IX1 (CODE(35)),
	  FOREIGN KEY (SYSTEM_USER_ID) REFERENCES SYSTEM_USER (ID),
	  FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGE (ID)
)
ENGINE=InnoDB;

CREATE TABLE SYSTEM_USER_GROUP (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  GROUP_ID	 				INT(11) NOT NULL,
	  USER_ID	 				INT(11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (GROUP_ID) REFERENCES SYSTEM_GROUP (ID),
	  FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER (ID),
	  UNIQUE INDEX SYSTEM_USER_GROUP_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE CURRENT_USER_SESSION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  USER_ID	 				INT(11) NOT NULL,
	  LOGIN_TIME         		TIMESTAMP NOT NULL,
	  LAST_ACTIVITY_TIME        TIMESTAMP NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (USER_ID) REFERENCES SYSTEM_USER (ID)
)
ENGINE=InnoDB;