DROP TABLE IF EXISTS TEMP_RELATED_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_RELATED_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_TYPE;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_GROUP;
DROP TABLE IF EXISTS APPLICATION_ACTIVITY_GROUP_TYPE;
DROP TABLE IF EXISTS APPLICATION_FORM_FIELD;
DROP TABLE IF EXISTS APPLICATION_FORM_FIELD_TYPE;
DROP TABLE IF EXISTS APPLICATION_FORM;
DROP TABLE IF EXISTS APPLICATION_FORM_TYPE;
DROP TABLE IF EXISTS APPLICATION_ENTITY_FIELD;
DROP TABLE IF EXISTS APPLICATION_ENTITY_FIELD_TYPE;
DROP TABLE IF EXISTS APPLICATION_ENTITY;
DROP TABLE IF EXISTS APPLICATION_MODULE;
DROP TABLE IF EXISTS DATA_INPUT_JOB;
DROP TABLE IF EXISTS DATA_SOURCE;
DROP TABLE IF EXISTS DATA_SOURCE_FIELD;
DROP TABLE IF EXISTS DATA_SOURCE_FIELD_TYPE;
DROP TABLE IF EXISTS DATA_SOURCE_STRUCTURE;
DROP TABLE IF EXISTS DATA_SOURCE_TYPE;
DROP TABLE IF EXISTS DATA_SOURCE_CATEGORY;
DROP TABLE IF EXISTS MESSAGE;
DROP TABLE IF EXISTS MESSAGE_STATUS;
DROP TABLE IF EXISTS MESSAGE_TYPE;
DROP TABLE IF EXISTS EXTERNAL_SERVICE_USER;
DROP TABLE IF EXISTS EXTERNAL_TRANSACTION;
DROP TABLE IF EXISTS ADVICE;
DROP TABLE IF EXISTS ADVICE_STATUS;
DROP TABLE IF EXISTS ADVICE_TYPE_TAG;
DROP TABLE IF EXISTS ADVICE_TYPE;
DROP TABLE IF EXISTS SERVICE_TRANSACTION;
DROP TABLE IF EXISTS SERVICE_TRANSACTION_TYPE;
DROP TABLE IF EXISTS SERVICE_PEER;
DROP TABLE IF EXISTS HOST;
DROP TABLE IF EXISTS HOST_TYPE;
DROP TABLE IF EXISTS SERVICE;
DROP TABLE IF EXISTS SERVICE_MODE;
DROP TABLE IF EXISTS SERVICE_PROTOCOL_ADAPTER;
DROP TABLE IF EXISTS SERVICE_TYPE;
DROP TABLE IF EXISTS SERVICE_CATEGORY;
DROP TABLE IF EXISTS CUSTOMER_BLACKLIST;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS CUSTOMER_CLASSIFICATION;
DROP TABLE IF EXISTS CUSTOMER_TYPE;
DROP TABLE IF EXISTS SERVICE_CHANNEL;
DROP TABLE IF EXISTS STATUS_TYPE;
DROP TABLE IF EXISTS COUNTRY;
DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY ( 
	ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	CODE    				VARCHAR(3) NOT NULL,
	NAME	    			VARCHAR(35) NOT NULL,
	CRNCY_SYM   			VARCHAR(1) NULL,
	REMARKS        			VARCHAR(255) NULL,
	EFFECTIVE_DT   			DATE NOT NULL,
	REC_ST         			CHAR(1) NOT NULL,
	VERSION_NO     			INT(11) NULL,
	ROW_TS         			TIMESTAMP  NULL,
	CREATED_DT        		DATE NOT NULL,
	CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	LAST_MODIFIED_USR       VARCHAR(35) NULL,
	PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE COUNTRY ( 
	  ID      				INT(11) AUTO_INCREMENT NOT NULL,
	  CODE      			VARCHAR(3) NOT NULL, 
	  NAME		      		VARCHAR(75) NOT NULL,
	  CNTRY_CD_ISO2 		VARCHAR(2) NOT NULL,
	  CNTRY_CD_ISO3 		VARCHAR(3) NULL,
	  LOCAL_CRNCY_ID		INT(11) NULL,
	  REMARKS        		VARCHAR(255) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (LOCAL_CRNCY_ID) REFERENCES CURRENCY(ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_CHANNEL (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(75) NOT  NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_CHL_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE STATUS_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_TYPE (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_CLASSIFICATION (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_TY_ID				INT (11) NOT NULL,
	  CUST_CLASS_ID				INT (11) NOT NULL,
	  CODE 						VARCHAR(35) NOT NULL,
	  NAME 						VARCHAR(75) NOT NULL,
	  EMAIL 					VARCHAR(50) NOT NULL,
	  MOBILE 					VARCHAR(15) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			CHAR(1) NOT NULL,
	  VERSION_NO     			INT(11) NULL,
	  ROW_TS         			TIMESTAMP  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR       	VARCHAR(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CUST_TY_ID) REFERENCES CUSTOMER_TYPE (ID),
	  FOREIGN KEY (CUST_CLASS_ID) REFERENCES CUSTOMER_CLASSIFICATION (ID)
)
ENGINE=InnoDB;

CREATE TABLE CUSTOMER_BLACKLIST (
	  ID	 					INT(11) AUTO_INCREMENT NOT NULL,
	  CUST_ID					INT (11) NOT NULL,
	  CODE    					VARCHAR(35) NOT  NULL,
	  DESCRIPTION				VARCHAR(200) NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY(ID),
	  FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER (ID),
	  UNIQUE INDEX CUSTOMER_BLACKLIST_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_CATEGORY (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_CATEGORY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_PROTOCOL_ADAPTER (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(50) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  CLASS_NAME 			VARCHAR(150) NOT  NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_PROTOCOL_ADAPTER_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_MODE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_MODE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  SERVICE_TY_ID		 	INT (11)  NOT NULL,
	  SERVICE_CATEGORY_ID	INT (11)  NOT NULL,
	  MODE_ID		 		INT (11)  NOT NULL,
	  ADAPTER_ID		 	INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  PORT_NO				INT(6) NOT NULL,
	  IP_ADDRESS			VARCHAR(15) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_IX1 (CODE(35)),
	  FOREIGN KEY (SERVICE_TY_ID) REFERENCES SERVICE_TYPE (ID),
	  FOREIGN KEY (SERVICE_CATEGORY_ID) REFERENCES SERVICE_CATEGORY (ID),
	  FOREIGN KEY (MODE_ID) REFERENCES SERVICE_MODE (ID),
	  FOREIGN KEY (ADAPTER_ID) REFERENCES SERVICE_PROTOCOL_ADAPTER (ID)
)
ENGINE=InnoDB;

CREATE TABLE HOST_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX HOST_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE HOST (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  HOST_TY_ID		 	INT (11)  NOT NULL,
	  ADAPTER_ID		 	INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  PORT_NO				INT(16) NOT NULL,
	  IP_ADDRESS			VARCHAR(15) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX HOST_IX1 (CODE(35)),
	  FOREIGN KEY (HOST_TY_ID) REFERENCES HOST_TYPE (ID),
	  FOREIGN KEY (ADAPTER_ID) REFERENCES SERVICE_PROTOCOL_ADAPTER (ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_PEER (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  SERVICE_ID			INT(11) NOT NULL,
	  HOST_ID				INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_PEER_IX1 (CODE(35)),
	  UNIQUE INDEX SERVICE_PEER_IX2 (SERVICE_ID, HOST_ID),
	  FOREIGN KEY (HOST_ID) REFERENCES HOST (ID),
	  FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (ID)
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TRANSACTION_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE SERVICE_TRANSACTION (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  TXN_TY_ID				INT(11) NOT NULL,
	  SERVICE_ID			INT(11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  AMOUNT				DECIMAL(38, 2) NOT NULL,
	  TXN_DATE				DATE NOT NULL,
	  ACCOUNT_NO			VARCHAR(75) NOT NULL,
	  ACCOUNT_NM			VARCHAR(75) NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX SERVICE_TXN_IX1 (CODE(35)),
	  FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE (ID),
	  FOREIGN KEY (TXN_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  TXN_TY_ID				INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  REQ_FEEDBACK			CHAR(1) NULL,
	  FEEDBACK_MSG			VARCHAR(255) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_TY_IX1 (CODE(35)),
	  FOREIGN KEY (TXN_TY_ID) REFERENCES SERVICE_TRANSACTION_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_TYPE_TAG (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  ADVICE_TY_ID 			INT (11)  NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  ADVICE_TY_TAG_VAL 	TEXT NOT  NULL,
	  IS_REGEX_FG         	char(1) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_TY_TAG_IX1 (CODE(35)),
	  FOREIGN KEY (ADVICE_TY_ID) REFERENCES ADVICE_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE ADVICE_STATUS (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX ADVICE_ST_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE ADVICE (
	  ID				 		INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 						VARCHAR(35) NOT  NULL,
	  NAME 						VARCHAR(75) NOT  NULL,
	  DESCRIPTION				VARCHAR(150) NULL,
	  COMM_EVENT_ID				INT (11) NOT NULL,
	  ADVICE_TY_ID				INT (11) NOT NULL,
	  ADVICE_ST_ID				INT (11) NOT NULL,
	  CUSTOMER_ID				INT (11) NOT NULL,
	  ADVICE_TXT		    	TEXT NULL,
	  CARD_NO				    VARCHAR(35) NULL,
	  ACCOUNT_NO				VARCHAR(35) NOT NULL,
	  CHEQUE_NO					VARCHAR(35) NULL,
	  ACCOUNT_NM				VARCHAR(75) NULL,
	  AMOUNT 					DECIMAL(38,2) NOT NULL,
	  EFFECTIVE_DT        		DATE NOT NULL,
	  REC_ST         			char(1) NOT NULL,
	  VERSION_NO     			int(11) NULL,
	  ROW_TS         			timestamp  NULL,
	  CREATED_DT        		DATE NOT NULL,
	  CREATED_BY_USR  	 		varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 			timestamp  NULL,	
	  LAST_MODIFIED_USR         varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (ADVICE_TY_ID) REFERENCES ADVICE_TYPE (ID),
	  FOREIGN KEY (ADVICE_ST_ID) REFERENCES ADVICE_STATUS (ID),
	  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
	  UNIQUE INDEX ADVICE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE MESSAGE_TYPE (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_TYPE_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE MESSAGE_STATUS (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_STATUS_IX1 (NAME(75)),
	  UNIQUE INDEX MESSAGE_STATUS_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE MESSAGE (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  MSG_TY_ID				INT (11) NOT NULL,
	  MSG_STATUS_ID		 	INT (11) NOT NULL,
	  ADVICE_ID		 		INT (11) NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  MESSAGE_FROM 			VARCHAR(75) NOT  NULL,
	  MESSAGE_TO 			VARCHAR(75) NOT  NULL,
	  MESSAGE_SUBJECT 		VARCHAR(100) NULL,
	  MESSAGE_TXT			VARCHAR(255) NOT  NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX MESSAGE_IX2 (CODE(35)),
	  FOREIGN KEY (ADVICE_ID) REFERENCES ADVICE (ID),
	  FOREIGN KEY (MSG_TY_ID) REFERENCES MESSAGE_TYPE (ID),
	  FOREIGN KEY (MSG_STATUS_ID) REFERENCES MESSAGE_STATUS (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_SOURCE_CATEGORY (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_SOURCE_CATEGORY_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_SOURCE_CATEGORY_IX3 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_SOURCE_STRUCTURE (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  DS_STRUCT_DELIMETER 	CHAR(1) NULL,
	  TARGET_ENTITY_CD	 	VARCHAR(35) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_SOURCE_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_SOURCE_TYPE_IX2 (CODE(35)),
	  UNIQUE INDEX DATA_SOURCE_TYPE_IX3 (TARGET_ENTITY_CD(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_SOURCE_FIELD_TYPE (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_SOURCE_FIELD_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_SOURCE_FIELD_TYPE_IX2 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE DATA_SOURCE_FIELD (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  DS_STRUCT_ID	 		INT (11) NOT NULL,
	  DS_FIELD_TY_ID 		INT (11) NOT NULL,
	  DS_FIELD_TARGET		VARCHAR(75) NOT  NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_SOURCE_FIELD_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_SOURCE_FIELD_IX2 (CODE(35)),
	  FOREIGN KEY (DS_STRUCT_ID) REFERENCES DATA_SOURCE_STRUCTURE (ID),
	  FOREIGN KEY (DS_FIELD_TY_ID) REFERENCES DATA_SOURCE_FIELD_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_SOURCE_TYPE (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  DS_CAT_ID 			INT(11) NOT  NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_SOURCE_TYPE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_SOURCE_TYPE_IX2 (CODE(35)),
	  FOREIGN KEY (DS_CAT_ID) REFERENCES DATA_SOURCE_CATEGORY (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_SOURCE (
	  ID				 	INT (11)  AUTO_INCREMENT NOT NULL,
	  DS_TY_ID 				INT(11) NOT  NULL,
	  DS_STRUCT_ID			INT (11) NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  DS_URL 				VARCHAR(75) NOT  NULL,
	  DS_DB 				VARCHAR(75) NULL,
	  DS_TBL_NM				VARCHAR(75) NULL,
	  USR_NM 				VARCHAR(75) NULL,
	  PASSWORD 				VARCHAR(75) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_SOURCE_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_SOURCE_IX2 (CODE(35)),
	  FOREIGN KEY (DS_TY_ID) REFERENCES DATA_SOURCE_TYPE (ID),
	  FOREIGN KEY (DS_STRUCT_ID) REFERENCES DATA_SOURCE_STRUCTURE (ID)
)
ENGINE=InnoDB;

CREATE TABLE DATA_INPUT_JOB (
	  ID 					INT (11) AUTO_INCREMENT NOT NULL,
	  DS_ID 				INT(11) NOT  NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  DI_FREQ_VAL			INT(11) NOT  NULL,
	  DI_FREQ_CD			VARCHAR(35) NOT  NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX DATA_INPUT_JOB_IX1 (NAME(75)),
	  UNIQUE INDEX DATA_INPUT_JOB_IX2 (CODE(35)),
	  FOREIGN KEY (DS_ID) REFERENCES DATA_SOURCE (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_MODULE (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  SEQUENCE_NO 			INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(50) NOT  NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  DISPLAY_FG 			CHAR (1)  NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  UNIQUE INDEX APPLICATION_MODULE_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(150) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_NM_PLURAL		VARCHAR(75) NOT  NULL,
	  HAS_TABLE				CHAR(1) NOT  NULL,
	  DB_NAME				CHAR(50) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  UNIQUE INDEX APPLICATION_ENTITY_U01 (CODE(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY_FIELD_TYPE
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ENTITY_FIELD
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  FIELD_TY_ID			INT(11) NOT NULL,
	  ENTITY_ID 			INT(11)  NOT NULL,
	  RELATED_ENTITY_ID		INT(11)  NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  PRIMARYKEY_FG			CHAR(1) NOT NULL,
	  STORAGE				CHAR(35) NOT NULL,
	  REQUIRED_FG			CHAR(1) NOT NULL,
	  UNIQUE_FG				CHAR(1) NULL,
	  RELATED_FG			CHAR(1) NULL,
	  SIZE					INT(11) NULL,
	  MAX_DIGITS			INT(11) NULL,
	  DECIMAL_PRECISION		INT(11) NULL,
	  SEQUENCE_NO			INT(11) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_IX1 (CODE(75)),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (RELATED_ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (FIELD_TY_ID) REFERENCES APPLICATION_ENTITY_FIELD_TYPE (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_TYPE
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FORM_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_ENTITY_FORM_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID				INT (11)  NOT NULL,
	  FORM_TY_ID			INT (11)  NOT NULL,
	  ENTITY_ID				INT (11)  NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_NM_PLURAL		VARCHAR(75) NOT  NULL,
	  HAS_TABLE				CHAR(1) NOT  NULL,
	  DB_NAME				CHAR(50) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (FORM_TY_ID) REFERENCES APPLICATION_FORM_TYPE (ID),
	  UNIQUE INDEX APPLICATION_FORM_U01 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_FIELD_TYPE
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_FORM_FIELD_TY_U01 (CODE(35)),
	  UNIQUE INDEX APPLICATION_FORM_FIELD_TY_U02 (NAME(75))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_FORM_FIELD
(
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  FIELD_TY_ID			INT(11) NOT NULL,
	  FORM_ID 				INT(11) NOT NULL,
	  ENTITY_FIELD_ID		INT(11) NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  PRIMARYKEY_FG			CHAR(1) NOT NULL,
	  REQUIRED_FG			CHAR(1) NOT NULL,
	  RELATED_FG			CHAR(1) NULL,
	  SIZE					INT(11) NULL,
	  MAX_DIGITS			INT(11) NULL,
	  DECIMAL_PRECISION		INT(11) NULL,
	  SEQUENCE_NO			INT(11) NOT NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ENTITY_FIELD_IX1 (CODE(75)),
	  FOREIGN KEY (FORM_ID) REFERENCES APPLICATION_FORM (ID),
	  FOREIGN KEY (FIELD_TY_ID) REFERENCES APPLICATION_FORM_FIELD_TYPE (ID),
	  FOREIGN KEY (ENTITY_FIELD_ID) REFERENCES APPLICATION_ENTITY_FIELD (ID)
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_GROUP_TYPE
(
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ACT_GRP_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_GROUP (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  PARENT_GRP_ID     	INT (11)  NULL,
	  GRP_TY_ID				INT (11) NOT NULL,
	  CODE 					VARCHAR(50) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION		    VARCHAR(100) NULL,
	  GRP_URL			    VARCHAR(255) NOT NULL,
	  GRP_SEQ 				INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  DISPLAY_FG 			CHAR (1)  NOT NULL,
	  IS_PARENT         	CHAR(1) NOT NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (PARENT_GRP_ID) REFERENCES APPLICATION_ACTIVITY_GROUP (ID),
	  FOREIGN KEY (GRP_TY_ID) REFERENCES APPLICATION_ACTIVITY_GROUP_TYPE (ID),
	  UNIQUE INDEX APPLICATION_ACT_GRP_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY_TYPE (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  CODE 					VARCHAR(35) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION			VARCHAR(150) NULL,
	  EFFECTIVE_DT   		DATE NOT NULL,
	  REC_ST         		CHAR(1) NOT NULL,
	  VERSION_NO     		INT(11) NULL,
	  ROW_TS         		TIMESTAMP  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	VARCHAR(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		TIMESTAMP  NULL,	
	  LAST_MODIFIED_USR     VARCHAR(35) NULL,
	  PRIMARY KEY( ID ),
	  UNIQUE INDEX APPLICATION_ACT_TY_IX1 (CODE(35))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_ACTIVITY (
	  ID		 			INT (11)  AUTO_INCREMENT NOT NULL,
	  MODULE_ID 			INT (11)  NOT NULL,
	  GRP_ID 			    INT (11)  NOT NULL,
	  ACTIVITY_TY_ID		INT (11)  NOT NULL,
	  ENTITY_ID 			INT (11)  NULL,
	  FORM_ID				INT (11)  NULL,
	  CODE 					VARCHAR(75) NOT  NULL,
	  NAME 					VARCHAR(150) NOT  NULL,
	  DESCRIPTION			VARCHAR(100) NULL,
	  ACTIVITY_URL		    VARCHAR(255) NULL,
	  ACTIVITY_SEQ 			INT (11)  NOT NULL DEFAULT 0,
	  DISPLAY_NM 			VARCHAR(75) NOT  NULL,
	  DISPLAY_IMG 			VARCHAR(35) NULL,
	  OPERATION_CD 			VARCHAR(35) NOT  NULL,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	        DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (MODULE_ID) REFERENCES APPLICATION_MODULE (ID),
	  FOREIGN KEY (GRP_ID) REFERENCES APPLICATION_ACTIVITY_GROUP (ID),
	  FOREIGN KEY (FORM_ID) REFERENCES APPLICATION_FORM (ID),
	  FOREIGN KEY (ENTITY_ID) REFERENCES APPLICATION_ENTITY (ID),
	  FOREIGN KEY (ACTIVITY_TY_ID) REFERENCES APPLICATION_ACTIVITY_TYPE (ID),
	  UNIQUE INDEX APPLICATION_ACTIVITY_IX1 (CODE(50))
)
ENGINE=InnoDB;

CREATE TABLE APPLICATION_RELATED_ACTIVITY (
	  ID 					INT (11)  AUTO_INCREMENT NOT NULL,
	  SRC_ACT_ID 			INT (11)  NULL,
	  DST_ACT_ID 			INT (11)  NULL,
	  CODE 					VARCHAR(150) NOT  NULL,
	  NAME 					VARCHAR(75) NOT  NULL,
	  DESCRIPTION 			VARCHAR(150) NOT  NULL,
	  REL_ACT_SEQ 			INT (11)  NOT NULL DEFAULT 0,
	  EFFECTIVE_DT        	DATE NOT NULL,
	  REC_ST         		char(1) NOT NULL,
	  VERSION_NO     		int(11) NULL,
	  ROW_TS         		timestamp  NULL,
	  CREATED_DT        	DATE NOT NULL,
	  CREATED_BY_USR  	 	varchar(35) NOT NULL, 	
	  LAST_MODIFIED_DT 		timestamp  NULL,	
	  LAST_MODIFIED_USR             varchar(35) NULL,
	  PRIMARY KEY (ID),
	  FOREIGN KEY (SRC_ACT_ID) REFERENCES APPLICATION_ACTIVITY (ID),
	  FOREIGN KEY (DST_ACT_ID) REFERENCES APPLICATION_ACTIVITY (ID),
	  UNIQUE INDEX RELATED_ACTIVITY_U01 (SRC_ACT_ID, DST_ACT_ID)
)
ENGINE=InnoDB;

CREATE TABLE TEMP_RELATED_ACTIVITY (
	  ID					INT (11)  AUTO_INCREMENT NOT NULL,
	  SOURCE_ACTIVITY		VARCHAR(75) NOT  NULL, 
	  DESTINATION_ACTIVITY	VARCHAR(75) NOT  NULL, 
	  RELATIONSHIP_TY		VARCHAR(75) NOT  NULL,
	  PRIMARY KEY (ID)
)
ENGINE=InnoDB;
