define({
    "root": {
	    /* App wide strings */
	    "alantra_label_submit": "Submit",
	    "alantra_label_list": "List",
	    "alantra_label_id": "Id",
	    "alantra_label_search": "Search",
	    "alantra_label_create": "Create",
	    "alantra_label_create_record": "Create New Record",
	    "alantra_label_edit": "Edit",
	    "alantra_label_delete": "Delete",
	    "alantra_label_manage": "Manage",
	    "alantra_label_cancel": "Cancel",
	    "alantra_form_field_required":"Please provide a value for ",
    
        
    
        	/* InvoiceRoleType user strings*/
    	"invoiceroletype": "Invoice Role Type",
	    "invoiceroletype_name": "Name",
	    "invoiceroletype_description": "Description",
	    "invoiceroletype_invoiceroles": "InvoiceRoles",
	    "invoiceroletype_id": "Id",
	    "invoiceroletype_code": "Code",
	    "invoiceroletype_effectivedt": "Effective Date",
	    "invoiceroletype_recst": "Status",
        "invoiceroletype_createddt": "Date Created",
		"invoiceroletype_createdbyusr": "Created By",
		"invoiceroletype_lastmodifieddt": "Last Modified",
		"invoiceroletype_lastmodifiedusr": "Last Modified By",
    	/* TermType user strings*/
    	"termtype": "Term Type",
	    "termtype_name": "Name",
	    "termtype_description": "Description",
	    "termtype_invoiceterms": "InvoiceTerms",
	    "termtype_id": "Id",
	    "termtype_code": "Code",
	    "termtype_effectivedt": "Effective Date",
	    "termtype_recst": "Status",
        "termtype_createddt": "Date Created",
		"termtype_createdbyusr": "Created By",
		"termtype_lastmodifieddt": "Last Modified",
		"termtype_lastmodifiedusr": "Last Modified By",
    	/* CommunicationEventType user strings*/
    	"communicationeventtype": "Communication Event Type",
	    "communicationeventtype_name": "Name",
	    "communicationeventtype_description": "Description",
	    "communicationeventtype_communicationevents": "CommunicationEvents",
	    "communicationeventtype_id": "Id",
	    "communicationeventtype_code": "Code",
	    "communicationeventtype_effectivedt": "Effective Date",
	    "communicationeventtype_recst": "Status",
        "communicationeventtype_createddt": "Date Created",
		"communicationeventtype_createdbyusr": "Created By",
		"communicationeventtype_lastmodifieddt": "Last Modified",
		"communicationeventtype_lastmodifiedusr": "Last Modified By",
    	/* PaymentApplication user strings*/
    	"paymentapplication": "Payment Application",
	    "paymentapplication_payment": "Payment",
	    "paymentapplication_billingaccount": "BillingAccount",
	    "paymentapplication_invoiceitem": "InvoiceItem",
	    "paymentapplication_description": "Description",
	    "paymentapplication_amountappl": "AmountAppl",
	    "paymentapplication_id": "Id",
	    "paymentapplication_code": "Code",
	    "paymentapplication_effectivedt": "Effective Date",
	    "paymentapplication_recst": "Status",
        "paymentapplication_createddt": "Date Created",
		"paymentapplication_createdbyusr": "Created By",
		"paymentapplication_lastmodifieddt": "Last Modified",
		"paymentapplication_lastmodifiedusr": "Last Modified By",
    	/* PartyType user strings*/
    	"partytype": "Party Type",
	    "partytype_partytype": "PartyType",
	    "partytype_name": "Name",
	    "partytype_description": "Description",
	    "partytype_partyclassifications": "PartyClassifications",
	    "partytype_parties": "Parties",
	    "partytype_partytypes": "PartyTypes",
	    "partytype_id": "Id",
	    "partytype_code": "Code",
	    "partytype_effectivedt": "Effective Date",
	    "partytype_recst": "Status",
        "partytype_createddt": "Date Created",
		"partytype_createdbyusr": "Created By",
		"partytype_lastmodifieddt": "Last Modified",
		"partytype_lastmodifiedusr": "Last Modified By",
    	/* CostComponentType user strings*/
    	"costcomponenttype": "Cost Component Type",
	    "costcomponenttype_name": "Name",
	    "costcomponenttype_description": "Description",
	    "costcomponenttype_estimatedproductcosts": "EstimatedProductCosts",
	    "costcomponenttype_id": "Id",
	    "costcomponenttype_code": "Code",
	    "costcomponenttype_effectivedt": "Effective Date",
	    "costcomponenttype_recst": "Status",
        "costcomponenttype_createddt": "Date Created",
		"costcomponenttype_createdbyusr": "Created By",
		"costcomponenttype_lastmodifieddt": "Last Modified",
		"costcomponenttype_lastmodifiedusr": "Last Modified By",
    	/* InvoiceType user strings*/
    	"invoicetype": "Invoice Type",
	    "invoicetype_name": "Name",
	    "invoicetype_description": "Description",
	    "invoicetype_invoices": "Invoices",
	    "invoicetype_id": "Id",
	    "invoicetype_code": "Code",
	    "invoicetype_effectivedt": "Effective Date",
	    "invoicetype_recst": "Status",
        "invoicetype_createddt": "Date Created",
		"invoicetype_createdbyusr": "Created By",
		"invoicetype_lastmodifieddt": "Last Modified",
		"invoicetype_lastmodifiedusr": "Last Modified By",
    	/* OrderItemBilling user strings*/
    	"orderitembilling": "Order Item Billing",
	    "orderitembilling_invoiceitem": "InvoiceItem",
	    "orderitembilling_productorderitem": "ProductOrderItem",
	    "orderitembilling_quantity": "Quantity",
	    "orderitembilling_amount": "Amount",
	    "orderitembilling_description": "Description",
	    "orderitembilling_id": "Id",
	    "orderitembilling_code": "Code",
	    "orderitembilling_effectivedt": "Effective Date",
	    "orderitembilling_recst": "Status",
        "orderitembilling_createddt": "Date Created",
		"orderitembilling_createdbyusr": "Created By",
		"orderitembilling_lastmodifieddt": "Last Modified",
		"orderitembilling_lastmodifiedusr": "Last Modified By",
    	/* CaseRole user strings*/
    	"caserole": "Case Role",
	    "caserole_party": "Party",
	    "caserole_caseroletype": "CaseRoleType",
	    "caserole_name": "Name",
	    "caserole_description": "Description",
	    "caserole_partycases": "PartyCases",
	    "caserole_id": "Id",
	    "caserole_code": "Code",
	    "caserole_effectivedt": "Effective Date",
	    "caserole_recst": "Status",
        "caserole_createddt": "Date Created",
		"caserole_createdbyusr": "Created By",
		"caserole_lastmodifieddt": "Last Modified",
		"caserole_lastmodifiedusr": "Last Modified By",
    	/* WorkEffort user strings*/
    	"workeffort": "Work Effort",
	    "workeffort_workefforttype": "WorkEffortType",
	    "workeffort_name": "Name",
	    "workeffort_description": "Description",
	    "workeffort_schedstartdt": "SchedStartDt",
	    "workeffort_schedenddt": "SchedEndDt",
	    "workeffort_esthours": "EstHours",
	    "workeffort_totalhrallowed": "TotalHrAllowed",
	    "workeffort_totalamountallowed": "TotalAmountAllowed",
	    "workeffort_communicationeventworkefforts": "CommunicationEventWorkEfforts",
	    "workeffort_id": "Id",
	    "workeffort_code": "Code",
	    "workeffort_effectivedt": "Effective Date",
	    "workeffort_recst": "Status",
        "workeffort_createddt": "Date Created",
		"workeffort_createdbyusr": "Created By",
		"workeffort_lastmodifieddt": "Last Modified",
		"workeffort_lastmodifiedusr": "Last Modified By",
    	/* BillingAccount user strings*/
    	"billingaccount": "Billing Account",
	    "billingaccount_contmechid": "ContMechId",
	    "billingaccount_name": "Name",
	    "billingaccount_description": "Description",
	    "billingaccount_fromdt": "FromDt",
	    "billingaccount_thrudt": "ThruDt",
	    "billingaccount_billingaccountroles": "BillingAccountRoles",
	    "billingaccount_paymentapplications": "PaymentApplications",
	    "billingaccount_id": "Id",
	    "billingaccount_code": "Code",
	    "billingaccount_effectivedt": "Effective Date",
	    "billingaccount_recst": "Status",
        "billingaccount_createddt": "Date Created",
		"billingaccount_createdbyusr": "Created By",
		"billingaccount_lastmodifieddt": "Last Modified",
		"billingaccount_lastmodifiedusr": "Last Modified By",
    	/* InvoiceRole user strings*/
    	"invoicerole": "Invoice Role",
	    "invoicerole_invoiceroletype": "InvoiceRoleType",
	    "invoicerole_party": "Party",
	    "invoicerole_invoice": "Invoice",
	    "invoicerole_description": "Description",
	    "invoicerole_percentage": "Percentage",
	    "invoicerole_id": "Id",
	    "invoicerole_code": "Code",
	    "invoicerole_effectivedt": "Effective Date",
	    "invoicerole_recst": "Status",
        "invoicerole_createddt": "Date Created",
		"invoicerole_createdbyusr": "Created By",
		"invoicerole_lastmodifieddt": "Last Modified",
		"invoicerole_lastmodifiedusr": "Last Modified By",
    	/* PartyCase user strings*/
    	"partycase": "Party Case",
	    "partycase_caserole": "CaseRole",
	    "partycase_communicationevent": "CommunicationEvent",
	    "partycase_casestatustype": "CaseStatusType",
	    "partycase_name": "Name",
	    "partycase_description": "Description",
	    "partycase_id": "Id",
	    "partycase_code": "Code",
	    "partycase_effectivedt": "Effective Date",
	    "partycase_recst": "Status",
        "partycase_createddt": "Date Created",
		"partycase_createdbyusr": "Created By",
		"partycase_lastmodifieddt": "Last Modified",
		"partycase_lastmodifiedusr": "Last Modified By",
    	/* ContactMechanismType user strings*/
    	"contactmechanismtype": "Contact Mechanism Type",
	    "contactmechanismtype_name": "Name",
	    "contactmechanismtype_description": "Description",
	    "contactmechanismtype_communicationevents": "CommunicationEvents",
	    "contactmechanismtype_contactmechanisms": "ContactMechanisms",
	    "contactmechanismtype_id": "Id",
	    "contactmechanismtype_code": "Code",
	    "contactmechanismtype_effectivedt": "Effective Date",
	    "contactmechanismtype_recst": "Status",
        "contactmechanismtype_createddt": "Date Created",
		"contactmechanismtype_createdbyusr": "Created By",
		"contactmechanismtype_lastmodifieddt": "Last Modified",
		"contactmechanismtype_lastmodifiedusr": "Last Modified By",
    	/* PaymentType user strings*/
    	"paymenttype": "Payment Type",
	    "paymenttype_name": "Name",
	    "paymenttype_description": "Description",
	    "paymenttype_payments": "Payments",
	    "paymenttype_id": "Id",
	    "paymenttype_code": "Code",
	    "paymenttype_effectivedt": "Effective Date",
	    "paymenttype_recst": "Status",
        "paymenttype_createddt": "Date Created",
		"paymenttype_createdbyusr": "Created By",
		"paymenttype_lastmodifieddt": "Last Modified",
		"paymenttype_lastmodifiedusr": "Last Modified By",
    	/* Currency user strings*/
    	"currency": "Currency",
	    "currency_crncynm": "CrncyNm",
	    "currency_crncysym": "CrncySym",
	    "currency_remarks": "Remarks",
	    "currency_id": "Id",
	    "currency_code": "Code",
	    "currency_effectivedt": "Effective Date",
	    "currency_recst": "Status",
        "currency_createddt": "Date Created",
		"currency_createdbyusr": "Created By",
		"currency_lastmodifieddt": "Last Modified",
		"currency_lastmodifiedusr": "Last Modified By",
    	/* PartyRole user strings*/
    	"partyrole": "Party Role",
	    "partyrole_partyroletype": "PartyRoleType",
	    "partyrole_party": "Party",
	    "partyrole_name": "Name",
	    "partyrole_description": "Description",
	    "partyrole_fromdt": "FromDt",
	    "partyrole_thrudt": "ThruDt",
	    "partyrole_partyrelationships": "PartyRelationships",
	    "partyrole_partyrelationships_1": "PartyRelationships_1",
	    "partyrole_id": "Id",
	    "partyrole_code": "Code",
	    "partyrole_effectivedt": "Effective Date",
	    "partyrole_recst": "Status",
        "partyrole_createddt": "Date Created",
		"partyrole_createdbyusr": "Created By",
		"partyrole_lastmodifieddt": "Last Modified",
		"partyrole_lastmodifiedusr": "Last Modified By",
    	/* ProductFeatureApplicabilityType user strings*/
    	"productfeatureapplicabilitytype": "Product Feature Applicability Type",
	    "productfeatureapplicabilitytype_name": "Name",
	    "productfeatureapplicabilitytype_description": "Description",
	    "productfeatureapplicabilitytype_productfeatureapplicabilities": "ProductFeatureApplicabilities",
	    "productfeatureapplicabilitytype_id": "Id",
	    "productfeatureapplicabilitytype_code": "Code",
	    "productfeatureapplicabilitytype_effectivedt": "Effective Date",
	    "productfeatureapplicabilitytype_recst": "Status",
        "productfeatureapplicabilitytype_createddt": "Date Created",
		"productfeatureapplicabilitytype_createdbyusr": "Created By",
		"productfeatureapplicabilitytype_lastmodifieddt": "Last Modified",
		"productfeatureapplicabilitytype_lastmodifiedusr": "Last Modified By",
    	/* Person user strings*/
    	"person": "Person",
	    "person_party": "Party",
	    "person_currentfnm": "CurrentFNm",
	    "person_currentlnm": "CurrentLNm",
	    "person_currentmnm": "CurrentMNm",
	    "person_currentsuffix": "CurrentSuffix",
	    "person_currentptitle": "CurrentPtitle",
	    "person_currentnnm": "CurrentNNm",
	    "person_mothermaidennm": "MotherMaidenNm",
	    "person_gender": "Gender",
	    "person_maritalst": "MaritalSt",
	    "person_ssno": "SsNo",
	    "person_currentppno": "CurrentPpNo",
	    "person_currentppexpdt": "CurrentPpExpDt",
	    "person_weight": "Weight",
	    "person_height": "Height",
	    "person_birthdt": "BirthDt",
	    "person_totyrworkexp": "TotYrWorkExp",
	    "person_remarks": "Remarks",
	    "person_id": "Id",
	    "person_code": "Code",
	    "person_effectivedt": "Effective Date",
	    "person_recst": "Status",
        "person_createddt": "Date Created",
		"person_createdbyusr": "Created By",
		"person_lastmodifieddt": "Last Modified",
		"person_lastmodifiedusr": "Last Modified By",
    	/* Product user strings*/
    	"product": "Product",
	    "product_producttype": "ProductType",
	    "product_name": "Name",
	    "product_description": "Description",
	    "product_introductiondt": "IntroductionDt",
	    "product_discountinueddt": "DiscountinuedDt",
	    "product_productclassifications": "ProductClassifications",
	    "product_estimatedproductcosts": "EstimatedProductCosts",
	    "product_productcomponentsforforprodid": "ProductComponentsForForProdId",
	    "product_productorderitems": "ProductOrderItems",
	    "product_productfeatureapplicabilities": "ProductFeatureApplicabilities",
	    "product_productcomponentsforinprodid": "ProductComponentsForInProdId",
	    "product_invoiceitems": "InvoiceItems",
	    "product_id": "Id",
	    "product_code": "Code",
	    "product_effectivedt": "Effective Date",
	    "product_recst": "Status",
        "product_createddt": "Date Created",
		"product_createdbyusr": "Created By",
		"product_lastmodifieddt": "Last Modified",
		"product_lastmodifiedusr": "Last Modified By",
    	/* InvoiceItemType user strings*/
    	"invoiceitemtype": "Invoice  Item Type",
	    "invoiceitemtype_name": "Name",
	    "invoiceitemtype_description": "Description",
	    "invoiceitemtype_invoiceitems": "InvoiceItems",
	    "invoiceitemtype_id": "Id",
	    "invoiceitemtype_code": "Code",
	    "invoiceitemtype_effectivedt": "Effective Date",
	    "invoiceitemtype_recst": "Status",
        "invoiceitemtype_createddt": "Date Created",
		"invoiceitemtype_createdbyusr": "Created By",
		"invoiceitemtype_lastmodifieddt": "Last Modified",
		"invoiceitemtype_lastmodifiedusr": "Last Modified By",
    	/* EstimatedProductCost user strings*/
    	"estimatedproductcost": "Estimated Product Cost",
	    "estimatedproductcost_product": "Product",
	    "estimatedproductcost_costcomponenttype": "CostComponentType",
	    "estimatedproductcost_productfeature": "ProductFeature",
	    "estimatedproductcost_geoboundry": "GeoBoundry",
	    "estimatedproductcost_cost": "Cost",
	    "estimatedproductcost_description": "Description",
	    "estimatedproductcost_fromdt": "FromDt",
	    "estimatedproductcost_todt": "ToDt",
	    "estimatedproductcost_id": "Id",
	    "estimatedproductcost_code": "Code",
	    "estimatedproductcost_effectivedt": "Effective Date",
	    "estimatedproductcost_recst": "Status",
        "estimatedproductcost_createddt": "Date Created",
		"estimatedproductcost_createdbyusr": "Created By",
		"estimatedproductcost_lastmodifieddt": "Last Modified",
		"estimatedproductcost_lastmodifiedusr": "Last Modified By",
    	/* PartyRelationship user strings*/
    	"partyrelationship": "Party Relationship",
	    "partyrelationship_partyrole": "PartyRole",
	    "partyrelationship_partyrelationshiptype": "PartyRelationshipType",
	    "partyrelationship_toroleid": "ToRoleId",
	    "partyrelationship_name": "Name",
	    "partyrelationship_description": "Description",
	    "partyrelationship_comment": "Comment",
	    "partyrelationship_fromdt": "FromDt",
	    "partyrelationship_thrudt": "ThruDt",
	    "partyrelationship_communicationevents": "CommunicationEvents",
	    "partyrelationship_id": "Id",
	    "partyrelationship_code": "Code",
	    "partyrelationship_effectivedt": "Effective Date",
	    "partyrelationship_recst": "Status",
        "partyrelationship_createddt": "Date Created",
		"partyrelationship_createdbyusr": "Created By",
		"partyrelationship_lastmodifieddt": "Last Modified",
		"partyrelationship_lastmodifiedusr": "Last Modified By",
    	/* StatusType user strings*/
    	"statustype": "Status Type",
	    "statustype_name": "Name",
	    "statustype_description": "Description",
	    "statustype_id": "Id",
	    "statustype_code": "Code",
	    "statustype_effectivedt": "Effective Date",
	    "statustype_recst": "Status",
        "statustype_createddt": "Date Created",
		"statustype_createdbyusr": "Created By",
		"statustype_lastmodifieddt": "Last Modified",
		"statustype_lastmodifiedusr": "Last Modified By",
    	/* ContactMechanismPurposeType user strings*/
    	"contactmechanismpurposetype": "Conatact Mechanism Purpose Type",
	    "contactmechanismpurposetype_name": "Name",
	    "contactmechanismpurposetype_description": "Description",
	    "contactmechanismpurposetype_partycontactmechanismpurposes": "PartyContactMechanismPurposes",
	    "contactmechanismpurposetype_id": "Id",
	    "contactmechanismpurposetype_code": "Code",
	    "contactmechanismpurposetype_effectivedt": "Effective Date",
	    "contactmechanismpurposetype_recst": "Status",
        "contactmechanismpurposetype_createddt": "Date Created",
		"contactmechanismpurposetype_createdbyusr": "Created By",
		"contactmechanismpurposetype_lastmodifieddt": "Last Modified",
		"contactmechanismpurposetype_lastmodifiedusr": "Last Modified By",
    	/* BaseEntity user strings*/
    	"baseentity": "baseentity",
	    "baseentity_id": "Id",
	    "baseentity_code": "Code",
	    "baseentity_effectivedt": "Effective Date",
	    "baseentity_recst": "Status",
        "baseentity_createddt": "Date Created",
		"baseentity_createdbyusr": "Created By",
		"baseentity_lastmodifieddt": "Last Modified",
		"baseentity_lastmodifiedusr": "Last Modified By",
    	/* ElectronicAddress user strings*/
    	"electronicaddress": "Electronic Address",
	    "electronicaddress_contactmechanism": "ContactMechanism",
	    "electronicaddress_elecaddrtxt": "ElecAddrTxt",
	    "electronicaddress_description": "Description",
	    "electronicaddress_id": "Id",
	    "electronicaddress_code": "Code",
	    "electronicaddress_effectivedt": "Effective Date",
	    "electronicaddress_recst": "Status",
        "electronicaddress_createddt": "Date Created",
		"electronicaddress_createdbyusr": "Created By",
		"electronicaddress_lastmodifieddt": "Last Modified",
		"electronicaddress_lastmodifiedusr": "Last Modified By",
    	/* RoleType user strings*/
    	"roletype": "Role Type",
	    "roletype_name": "Name",
	    "roletype_description": "Description",
	    "roletype_partyroletypes": "PartyRoleTypes",
	    "roletype_id": "Id",
	    "roletype_code": "Code",
	    "roletype_effectivedt": "Effective Date",
	    "roletype_recst": "Status",
        "roletype_createddt": "Date Created",
		"roletype_createdbyusr": "Created By",
		"roletype_lastmodifieddt": "Last Modified",
		"roletype_lastmodifiedusr": "Last Modified By",
    	/* ContactMechanism user strings*/
    	"contactmechanism": "Contact Mechanism",
	    "contactmechanism_contactmechanismtype": "ContactMechanismType",
	    "contactmechanism_name": "Name",
	    "contactmechanism_description": "Description",
	    "contactmechanism_postaladdresses": "PostalAddresses",
	    "contactmechanism_partycontactmechanismpurposes": "PartyContactMechanismPurposes",
	    "contactmechanism_contactmechanismlinksfortoid": "ContactMechanismLinksForToId",
	    "contactmechanism_contactmechanismlinksforfromid": "ContactMechanismLinksForFromId",
	    "contactmechanism_invoices": "Invoices",
	    "contactmechanism_telecommunicationsnumbers": "TelecommunicationsNumbers",
	    "contactmechanism_electronicaddresses": "ElectronicAddresses",
	    "contactmechanism_partycontactmechanisms": "PartyContactMechanisms",
	    "contactmechanism_id": "Id",
	    "contactmechanism_code": "Code",
	    "contactmechanism_effectivedt": "Effective Date",
	    "contactmechanism_recst": "Status",
        "contactmechanism_createddt": "Date Created",
		"contactmechanism_createdbyusr": "Created By",
		"contactmechanism_lastmodifieddt": "Last Modified",
		"contactmechanism_lastmodifiedusr": "Last Modified By",
    	/* ProductOrderType user strings*/
    	"productordertype": "Product Order Type",
	    "productordertype_name": "Name",
	    "productordertype_description": "Description",
	    "productordertype_productorders": "ProductOrders",
	    "productordertype_id": "Id",
	    "productordertype_code": "Code",
	    "productordertype_effectivedt": "Effective Date",
	    "productordertype_recst": "Status",
        "productordertype_createddt": "Date Created",
		"productordertype_createdbyusr": "Created By",
		"productordertype_lastmodifieddt": "Last Modified",
		"productordertype_lastmodifiedusr": "Last Modified By",
    	/* InvoiceItemCategory user strings*/
    	"invoiceitemcategory": "Invoice Item Category",
	    "invoiceitemcategory_name": "Name",
	    "invoiceitemcategory_description": "Description",
	    "invoiceitemcategory_invoiceitems": "InvoiceItems",
	    "invoiceitemcategory_id": "Id",
	    "invoiceitemcategory_code": "Code",
	    "invoiceitemcategory_effectivedt": "Effective Date",
	    "invoiceitemcategory_recst": "Status",
        "invoiceitemcategory_createddt": "Date Created",
		"invoiceitemcategory_createdbyusr": "Created By",
		"invoiceitemcategory_lastmodifieddt": "Last Modified",
		"invoiceitemcategory_lastmodifiedusr": "Last Modified By",
    	/* PartyClassification user strings*/
    	"partyclassification": "Party Classification",
	    "partyclassification_partytype": "PartyType",
	    "partyclassification_partyclassificationtype": "PartyClassificationType",
	    "partyclassification_party": "Party",
	    "partyclassification_name": "Name",
	    "partyclassification_description": "Description",
	    "partyclassification_fromdt": "FromDt",
	    "partyclassification_thrudt": "ThruDt",
	    "partyclassification_id": "Id",
	    "partyclassification_code": "Code",
	    "partyclassification_effectivedt": "Effective Date",
	    "partyclassification_recst": "Status",
        "partyclassification_createddt": "Date Created",
		"partyclassification_createdbyusr": "Created By",
		"partyclassification_lastmodifieddt": "Last Modified",
		"partyclassification_lastmodifiedusr": "Last Modified By",
    	/* ProductClassification user strings*/
    	"productclassification": "Product Classification",
	    "productclassification_productcategory": "ProductCategory",
	    "productclassification_product": "Product",
	    "productclassification_name": "Name",
	    "productclassification_description": "Description",
	    "productclassification_remarks": "Remarks",
	    "productclassification_fromdt": "FromDt",
	    "productclassification_todt": "ToDt",
	    "productclassification_primaryfg": "PrimaryFg",
	    "productclassification_id": "Id",
	    "productclassification_code": "Code",
	    "productclassification_effectivedt": "Effective Date",
	    "productclassification_recst": "Status",
        "productclassification_createddt": "Date Created",
		"productclassification_createdbyusr": "Created By",
		"productclassification_lastmodifieddt": "Last Modified",
		"productclassification_lastmodifiedusr": "Last Modified By",
    	/* ProductFeature user strings*/
    	"productfeature": "Product Feature",
	    "productfeature_productfeaturetype": "ProductFeatureType",
	    "productfeature_productfeaturecategory": "ProductFeatureCategory",
	    "productfeature_name": "Name",
	    "productfeature_description": "Description",
	    "productfeature_estimatedproductcosts": "EstimatedProductCosts",
	    "productfeature_invoiceitems": "InvoiceItems",
	    "productfeature_productfeatureapplicabilities": "ProductFeatureApplicabilities",
	    "productfeature_productorderitems": "ProductOrderItems",
	    "productfeature_id": "Id",
	    "productfeature_code": "Code",
	    "productfeature_effectivedt": "Effective Date",
	    "productfeature_recst": "Status",
        "productfeature_createddt": "Date Created",
		"productfeature_createdbyusr": "Created By",
		"productfeature_lastmodifieddt": "Last Modified",
		"productfeature_lastmodifiedusr": "Last Modified By",
    	/* Uom user strings*/
    	"uom": "UOM",
	    "uom_name": "Name",
	    "uom_description": "Description",
	    "uom_id": "Id",
	    "uom_code": "Code",
	    "uom_effectivedt": "Effective Date",
	    "uom_recst": "Status",
        "uom_createddt": "Date Created",
		"uom_createdbyusr": "Created By",
		"uom_lastmodifieddt": "Last Modified",
		"uom_lastmodifiedusr": "Last Modified By",
    	/* ServiceChannel user strings*/
    	"servicechannel": "Service Channel",
	    "servicechannel_name": "Name",
	    "servicechannel_description": "Description",
	    "servicechannel_id": "Id",
	    "servicechannel_code": "Code",
	    "servicechannel_effectivedt": "Effective Date",
	    "servicechannel_recst": "Status",
        "servicechannel_createddt": "Date Created",
		"servicechannel_createdbyusr": "Created By",
		"servicechannel_lastmodifieddt": "Last Modified",
		"servicechannel_lastmodifiedusr": "Last Modified By",
    	/* BillingAccountRoleType user strings*/
    	"billingaccountroletype": "Billing Account Role Type",
	    "billingaccountroletype_name": "Name",
	    "billingaccountroletype_description": "Description",
	    "billingaccountroletype_billingaccountroles": "BillingAccountRoles",
	    "billingaccountroletype_id": "Id",
	    "billingaccountroletype_code": "Code",
	    "billingaccountroletype_effectivedt": "Effective Date",
	    "billingaccountroletype_recst": "Status",
        "billingaccountroletype_createddt": "Date Created",
		"billingaccountroletype_createdbyusr": "Created By",
		"billingaccountroletype_lastmodifieddt": "Last Modified",
		"billingaccountroletype_lastmodifiedusr": "Last Modified By",
    	/* UomConversion user strings*/
    	"uomconversion": "UOM Conversion",
	    "uomconversion_fromuomid": "FromUomId",
	    "uomconversion_touomid": "ToUomId",
	    "uomconversion_conversionfactor": "ConversionFactor",
	    "uomconversion_name": "Name",
	    "uomconversion_description": "Description",
	    "uomconversion_id": "Id",
	    "uomconversion_code": "Code",
	    "uomconversion_effectivedt": "Effective Date",
	    "uomconversion_recst": "Status",
        "uomconversion_createddt": "Date Created",
		"uomconversion_createdbyusr": "Created By",
		"uomconversion_lastmodifieddt": "Last Modified",
		"uomconversion_lastmodifiedusr": "Last Modified By",
    	/* CustomerBlacklist user strings*/
    	"customerblacklist": "Customer BlackList",
	    "customerblacklist_party": "Party",
	    "customerblacklist_description": "Description",
	    "customerblacklist_id": "Id",
	    "customerblacklist_code": "Code",
	    "customerblacklist_effectivedt": "Effective Date",
	    "customerblacklist_recst": "Status",
        "customerblacklist_createddt": "Date Created",
		"customerblacklist_createdbyusr": "Created By",
		"customerblacklist_lastmodifieddt": "Last Modified",
		"customerblacklist_lastmodifiedusr": "Last Modified By",
    	/* PostalAddress user strings*/
    	"postaladdress": "Postal Address",
	    "postaladdress_contactmechanism": "ContactMechanism",
	    "postaladdress_address1": "Address 1",
	    "postaladdress_address2": "Address 2",
	    "postaladdress_directions": "Directions",
	    "postaladdress_description": "Description",
	    "postaladdress_postaladdressboundries": "PostalAddressBoundries",
	    "postaladdress_id": "Id",
	    "postaladdress_code": "Code",
	    "postaladdress_effectivedt": "Effective Date",
	    "postaladdress_recst": "Status",
        "postaladdress_createddt": "Date Created",
		"postaladdress_createdbyusr": "Created By",
		"postaladdress_lastmodifieddt": "Last Modified",
		"postaladdress_lastmodifiedusr": "Last Modified By",
    	/* ProductFeatureApplicability user strings*/
    	"productfeatureapplicability": "Product Feature Applicability",
	    "productfeatureapplicability_product": "Product",
	    "productfeatureapplicability_productfeature": "ProductFeature",
	    "productfeatureapplicability_productfeatureapplicabilitytype": "ProductFeatureApplicabilityType",
	    "productfeatureapplicability_name": "Name",
	    "productfeatureapplicability_description": "Description",
	    "productfeatureapplicability_fromdt": "FromDt",
	    "productfeatureapplicability_todt": "ToDt",
	    "productfeatureapplicability_id": "Id",
	    "productfeatureapplicability_code": "Code",
	    "productfeatureapplicability_effectivedt": "Effective Date",
	    "productfeatureapplicability_recst": "Status",
        "productfeatureapplicability_createddt": "Date Created",
		"productfeatureapplicability_createdbyusr": "Created By",
		"productfeatureapplicability_lastmodifieddt": "Last Modified",
		"productfeatureapplicability_lastmodifiedusr": "Last Modified By",
    	/* GeoBoundry user strings*/
    	"geoboundry": "Geo Boundry",
	    "geoboundry_geoboundarytype": "GeoBoundaryType",
	    "geoboundry_name": "Name",
	    "geoboundry_abbreviation": "Abbreviation",
	    "geoboundry_description": "Description",
	    "geoboundry_postaladdressboundries": "PostalAddressBoundries",
	    "geoboundry_estimatedproductcosts": "EstimatedProductCosts",
	    "geoboundry_geoboundryassociationsforfromgeoid": "GeoBoundryAssociationsForFromGeoId",
	    "geoboundry_geoboundryassociationsfortogeoid": "GeoBoundryAssociationsForToGeoId",
	    "geoboundry_id": "Id",
	    "geoboundry_code": "Code",
	    "geoboundry_effectivedt": "Effective Date",
	    "geoboundry_recst": "Status",
        "geoboundry_createddt": "Date Created",
		"geoboundry_createdbyusr": "Created By",
		"geoboundry_lastmodifieddt": "Last Modified",
		"geoboundry_lastmodifiedusr": "Last Modified By",
    	/* CommunicationEventPurposeType user strings*/
    	"communicationeventpurposetype": "Communication Event Purpose Type",
	    "communicationeventpurposetype_name": "Name",
	    "communicationeventpurposetype_description": "Description",
	    "communicationeventpurposetype_communicationeventpurposes": "CommunicationEventPurposes",
	    "communicationeventpurposetype_id": "Id",
	    "communicationeventpurposetype_code": "Code",
	    "communicationeventpurposetype_effectivedt": "Effective Date",
	    "communicationeventpurposetype_recst": "Status",
        "communicationeventpurposetype_createddt": "Date Created",
		"communicationeventpurposetype_createdbyusr": "Created By",
		"communicationeventpurposetype_lastmodifieddt": "Last Modified",
		"communicationeventpurposetype_lastmodifiedusr": "Last Modified By",
    	/* ProductCategoryType user strings*/
    	"productcategorytype": "Product Category Type",
	    "productcategorytype_name": "Name",
	    "productcategorytype_description": "Description",
	    "productcategorytype_productcategories": "ProductCategories",
	    "productcategorytype_id": "Id",
	    "productcategorytype_code": "Code",
	    "productcategorytype_effectivedt": "Effective Date",
	    "productcategorytype_recst": "Status",
        "productcategorytype_createddt": "Date Created",
		"productcategorytype_createdbyusr": "Created By",
		"productcategorytype_lastmodifieddt": "Last Modified",
		"productcategorytype_lastmodifiedusr": "Last Modified By",
    	/* ProductCategory user strings*/
    	"productcategory": "Product Category",
	    "productcategory_productcategorytype": "ProductCategoryType",
	    "productcategory_name": "Name",
	    "productcategory_description": "Description",
	    "productcategory_productclassifications": "ProductClassifications",
	    "productcategory_id": "Id",
	    "productcategory_code": "Code",
	    "productcategory_effectivedt": "Effective Date",
	    "productcategory_recst": "Status",
        "productcategory_createddt": "Date Created",
		"productcategory_createdbyusr": "Created By",
		"productcategory_lastmodifieddt": "Last Modified",
		"productcategory_lastmodifiedusr": "Last Modified By",
    	/* Customer user strings*/
    	"customer": "Customer",
	    "customer_party": "Party",
	    "customer_id": "Id",
	    "customer_code": "Code",
	    "customer_effectivedt": "Effective Date",
	    "customer_recst": "Status",
        "customer_createddt": "Date Created",
		"customer_createdbyusr": "Created By",
		"customer_lastmodifieddt": "Last Modified",
		"customer_lastmodifiedusr": "Last Modified By",
    	/* PaymentMethodType user strings*/
    	"paymentmethodtype": "Payment Method Type",
	    "paymentmethodtype_name": "Name",
	    "paymentmethodtype_description": "Description",
	    "paymentmethodtype_payments": "Payments",
	    "paymentmethodtype_paymentmethodtypeproviders": "PaymentMethodTypeProviders",
	    "paymentmethodtype_id": "Id",
	    "paymentmethodtype_code": "Code",
	    "paymentmethodtype_effectivedt": "Effective Date",
	    "paymentmethodtype_recst": "Status",
        "paymentmethodtype_createddt": "Date Created",
		"paymentmethodtype_createdbyusr": "Created By",
		"paymentmethodtype_lastmodifieddt": "Last Modified",
		"paymentmethodtype_lastmodifiedusr": "Last Modified By",
    	/* TelecommunicationsNumber user strings*/
    	"telecommunicationsnumber": "Telecommunication Number",
	    "telecommunicationsnumber_contactmechanism": "ContactMechanism",
	    "telecommunicationsnumber_areacode": "AreaCode",
	    "telecommunicationsnumber_contactno": "ContactNo",
	    "telecommunicationsnumber_countrycd": "CountryCd",
	    "telecommunicationsnumber_description": "Description",
	    "telecommunicationsnumber_id": "Id",
	    "telecommunicationsnumber_code": "Code",
	    "telecommunicationsnumber_effectivedt": "Effective Date",
	    "telecommunicationsnumber_recst": "Status",
        "telecommunicationsnumber_createddt": "Date Created",
		"telecommunicationsnumber_createdbyusr": "Created By",
		"telecommunicationsnumber_lastmodifieddt": "Last Modified",
		"telecommunicationsnumber_lastmodifiedusr": "Last Modified By",
    	/* PartyRoleType user strings*/
    	"partyroletype": "Party Role Type",
	    "partyroletype_roletype": "RoleType",
	    "partyroletype_partyroletype": "PartyRoleType",
	    "partyroletype_name": "Name",
	    "partyroletype_description": "Description",
	    "partyroletype_partyroles": "PartyRoles",
	    "partyroletype_partyroletypes": "PartyRoleTypes",
	    "partyroletype_partyrelationshiptypesforfromroletyid": "PartyRelationshipTypesForFromRoleTyId",
	    "partyroletype_partyrelationshiptypesfortoroletyid": "PartyRelationshipTypesForToRoleTyId",
	    "partyroletype_id": "Id",
	    "partyroletype_code": "Code",
	    "partyroletype_effectivedt": "Effective Date",
	    "partyroletype_recst": "Status",
        "partyroletype_createddt": "Date Created",
		"partyroletype_createdbyusr": "Created By",
		"partyroletype_lastmodifieddt": "Last Modified",
		"partyroletype_lastmodifiedusr": "Last Modified By",
    	/* PartyClassificationType user strings*/
    	"partyclassificationtype": "Party Classification Type",
	    "partyclassificationtype_partyclassificationtype": "PartyClassificationType",
	    "partyclassificationtype_name": "Name",
	    "partyclassificationtype_description": "Description",
	    "partyclassificationtype_partyclassifications": "PartyClassifications",
	    "partyclassificationtype_partyclassificationtypes": "PartyClassificationTypes",
	    "partyclassificationtype_id": "Id",
	    "partyclassificationtype_code": "Code",
	    "partyclassificationtype_effectivedt": "Effective Date",
	    "partyclassificationtype_recst": "Status",
        "partyclassificationtype_createddt": "Date Created",
		"partyclassificationtype_createdbyusr": "Created By",
		"partyclassificationtype_lastmodifieddt": "Last Modified",
		"partyclassificationtype_lastmodifiedusr": "Last Modified By",
    	/* PartyRelationshipType user strings*/
    	"partyrelationshiptype": "Party Relationship Type",
	    "partyrelationshiptype_partyroletypebyfromroletyid": "PartyRoleTypeByFromRoleTyId",
	    "partyrelationshiptype_partyroletypebytoroletyid": "PartyRoleTypeByToRoleTyId",
	    "partyrelationshiptype_name": "Name",
	    "partyrelationshiptype_description": "Description",
	    "partyrelationshiptype_partyrelationships": "PartyRelationships",
	    "partyrelationshiptype_id": "Id",
	    "partyrelationshiptype_code": "Code",
	    "partyrelationshiptype_effectivedt": "Effective Date",
	    "partyrelationshiptype_recst": "Status",
        "partyrelationshiptype_createddt": "Date Created",
		"partyrelationshiptype_createdbyusr": "Created By",
		"partyrelationshiptype_lastmodifieddt": "Last Modified",
		"partyrelationshiptype_lastmodifiedusr": "Last Modified By",
    	/* CommunicationEventStatusType user strings*/
    	"communicationeventstatustype": "Communication Event Status Type",
	    "communicationeventstatustype_name": "Name",
	    "communicationeventstatustype_description": "Description",
	    "communicationeventstatustype_communicationevents": "CommunicationEvents",
	    "communicationeventstatustype_id": "Id",
	    "communicationeventstatustype_code": "Code",
	    "communicationeventstatustype_effectivedt": "Effective Date",
	    "communicationeventstatustype_recst": "Status",
        "communicationeventstatustype_createddt": "Date Created",
		"communicationeventstatustype_createdbyusr": "Created By",
		"communicationeventstatustype_lastmodifieddt": "Last Modified",
		"communicationeventstatustype_lastmodifiedusr": "Last Modified By",
    	/* ContactMechanismLink user strings*/
    	"contactmechanismlink": "Contact Mechanism Link",
	    "contactmechanismlink_contactmechanismbytoid": "ContactMechanismByToId",
	    "contactmechanismlink_contactmechanismbyfromid": "ContactMechanismByFromId",
	    "contactmechanismlink_description": "Description",
	    "contactmechanismlink_id": "Id",
	    "contactmechanismlink_code": "Code",
	    "contactmechanismlink_effectivedt": "Effective Date",
	    "contactmechanismlink_recst": "Status",
        "contactmechanismlink_createddt": "Date Created",
		"contactmechanismlink_createdbyusr": "Created By",
		"contactmechanismlink_lastmodifieddt": "Last Modified",
		"contactmechanismlink_lastmodifiedusr": "Last Modified By",
    	/* CommunicationEventWorkEffort user strings*/
    	"communicationeventworkeffort": "Communciation Event WorkEffort",
	    "communicationeventworkeffort_workeffort": "WorkEffort",
	    "communicationeventworkeffort_communicationevent": "CommunicationEvent",
	    "communicationeventworkeffort_description": "Description",
	    "communicationeventworkeffort_id": "Id",
	    "communicationeventworkeffort_code": "Code",
	    "communicationeventworkeffort_effectivedt": "Effective Date",
	    "communicationeventworkeffort_recst": "Status",
        "communicationeventworkeffort_createddt": "Date Created",
		"communicationeventworkeffort_createdbyusr": "Created By",
		"communicationeventworkeffort_lastmodifieddt": "Last Modified",
		"communicationeventworkeffort_lastmodifiedusr": "Last Modified By",
    	/* CaseStatusType user strings*/
    	"casestatustype": "Case Status Type",
	    "casestatustype_name": "Name",
	    "casestatustype_description": "Description",
	    "casestatustype_partycases": "PartyCases",
	    "casestatustype_id": "Id",
	    "casestatustype_code": "Code",
	    "casestatustype_effectivedt": "Effective Date",
	    "casestatustype_recst": "Status",
        "casestatustype_createddt": "Date Created",
		"casestatustype_createdbyusr": "Created By",
		"casestatustype_lastmodifieddt": "Last Modified",
		"casestatustype_lastmodifiedusr": "Last Modified By",
    	/* PartyContactMechanism user strings*/
    	"partycontactmechanism": "Party Contact Mechanism",
	    "partycontactmechanism_contactmechanism": "ContactMechanism",
	    "partycontactmechanism_party": "Party",
	    "partycontactmechanism_fromdt": "FromDt",
	    "partycontactmechanism_todt": "ToDt",
	    "partycontactmechanism_description": "Description",
	    "partycontactmechanism_nosolicitationfg": "NoSolicitationFg",
	    "partycontactmechanism_extension": "Extension",
	    "partycontactmechanism_remarks": "Remarks",
	    "partycontactmechanism_id": "Id",
	    "partycontactmechanism_code": "Code",
	    "partycontactmechanism_effectivedt": "Effective Date",
	    "partycontactmechanism_recst": "Status",
        "partycontactmechanism_createddt": "Date Created",
		"partycontactmechanism_createdbyusr": "Created By",
		"partycontactmechanism_lastmodifieddt": "Last Modified",
		"partycontactmechanism_lastmodifiedusr": "Last Modified By",
    	/* ProductComponent user strings*/
    	"productcomponent": "Product Component",
	    "productcomponent_productbyinprodid": "ProductByInProdId",
	    "productcomponent_productbyforprodid": "ProductByForProdId",
	    "productcomponent_locationid": "LocationId",
	    "productcomponent_description": "Description",
	    "productcomponent_instruction": "Instruction",
	    "productcomponent_remarks": "Remarks",
	    "productcomponent_quantitiyused": "QuantitiyUsed",
	    "productcomponent_fromdt": "FromDt",
	    "productcomponent_todt": "ToDt",
	    "productcomponent_id": "Id",
	    "productcomponent_code": "Code",
	    "productcomponent_effectivedt": "Effective Date",
	    "productcomponent_recst": "Status",
        "productcomponent_createddt": "Date Created",
		"productcomponent_createdbyusr": "Created By",
		"productcomponent_lastmodifieddt": "Last Modified",
		"productcomponent_lastmodifiedusr": "Last Modified By",
    	/* ProductFeatureType user strings*/
    	"productfeaturetype": "Product Feature Type",
	    "productfeaturetype_name": "Name",
	    "productfeaturetype_description": "Description",
	    "productfeaturetype_productfeatures": "ProductFeatures",
	    "productfeaturetype_id": "Id",
	    "productfeaturetype_code": "Code",
	    "productfeaturetype_effectivedt": "Effective Date",
	    "productfeaturetype_recst": "Status",
        "productfeaturetype_createddt": "Date Created",
		"productfeaturetype_createdbyusr": "Created By",
		"productfeaturetype_lastmodifieddt": "Last Modified",
		"productfeaturetype_lastmodifiedusr": "Last Modified By",
    	/* InvoiceTerm user strings*/
    	"invoiceterm": "Invoice Term",
	    "invoiceterm_termtype": "TermType",
	    "invoiceterm_termval": "TermVal",
	    "invoiceterm_description": "Description",
	    "invoiceterm_invoices": "Invoices",
	    "invoiceterm_id": "Id",
	    "invoiceterm_code": "Code",
	    "invoiceterm_effectivedt": "Effective Date",
	    "invoiceterm_recst": "Status",
        "invoiceterm_createddt": "Date Created",
		"invoiceterm_createdbyusr": "Created By",
		"invoiceterm_lastmodifieddt": "Last Modified",
		"invoiceterm_lastmodifiedusr": "Last Modified By",
    	/* ProductType user strings*/
    	"producttype": "Product Type",
	    "producttype_names": "Names",
	    "producttype_description": "Description",
	    "producttype_products": "Products",
	    "producttype_id": "Id",
	    "producttype_code": "Code",
	    "producttype_effectivedt": "Effective Date",
	    "producttype_recst": "Status",
        "producttype_createddt": "Date Created",
		"producttype_createdbyusr": "Created By",
		"producttype_lastmodifieddt": "Last Modified",
		"producttype_lastmodifiedusr": "Last Modified By",
    	/* BillingAccountRole user strings*/
    	"billingaccountrole": "Billing Account Role",
	    "billingaccountrole_billingaccountroletype": "BillingAccountRoleType",
	    "billingaccountrole_party": "Party",
	    "billingaccountrole_billingaccount": "BillingAccount",
	    "billingaccountrole_name": "Name",
	    "billingaccountrole_description": "Description",
	    "billingaccountrole_fromdt": "FromDt",
	    "billingaccountrole_thrudt": "ThruDt",
	    "billingaccountrole_id": "Id",
	    "billingaccountrole_code": "Code",
	    "billingaccountrole_effectivedt": "Effective Date",
	    "billingaccountrole_recst": "Status",
        "billingaccountrole_createddt": "Date Created",
		"billingaccountrole_createdbyusr": "Created By",
		"billingaccountrole_lastmodifieddt": "Last Modified",
		"billingaccountrole_lastmodifiedusr": "Last Modified By",
    	/* PostalAddressBoundry user strings*/
    	"postaladdressboundry": "Postal Address Boundry",
	    "postaladdressboundry_postaladdress": "PostalAddress",
	    "postaladdressboundry_geoboundry": "GeoBoundry",
	    "postaladdressboundry_description": "Description",
	    "postaladdressboundry_id": "Id",
	    "postaladdressboundry_code": "Code",
	    "postaladdressboundry_effectivedt": "Effective Date",
	    "postaladdressboundry_recst": "Status",
        "postaladdressboundry_createddt": "Date Created",
		"postaladdressboundry_createdbyusr": "Created By",
		"postaladdressboundry_lastmodifieddt": "Last Modified",
		"postaladdressboundry_lastmodifiedusr": "Last Modified By",
    	/* ProductOrderItem user strings*/
    	"productorderitem": "Product Order Item",
	    "productorderitem_productorderitemtype": "ProductOrderItemType",
	    "productorderitem_productorder": "ProductOrder",
	    "productorderitem_product": "Product",
	    "productorderitem_productfeature": "ProductFeature",
	    "productorderitem_name": "Name",
	    "productorderitem_description": "Description",
	    "productorderitem_quantity": "Quantity",
	    "productorderitem_unitprice": "UnitPrice",
	    "productorderitem_expectdeliverydt": "ExpectDeliveryDt",
	    "productorderitem_instructions": "Instructions",
	    "productorderitem_remarks": "Remarks",
	    "productorderitem_orderitembillings": "OrderItemBillings",
	    "productorderitem_id": "Id",
	    "productorderitem_code": "Code",
	    "productorderitem_effectivedt": "Effective Date",
	    "productorderitem_recst": "Status",
        "productorderitem_createddt": "Date Created",
		"productorderitem_createdbyusr": "Created By",
		"productorderitem_lastmodifieddt": "Last Modified",
		"productorderitem_lastmodifiedusr": "Last Modified By",
    	/* CommunicationEvent user strings*/
    	"communicationevent": "Communication Event",
	    "communicationevent_communicationeventtype": "CommunicationEventType",
	    "communicationevent_communicationeventpurpose": "CommunicationEventPurpose",
	    "communicationevent_contactmechanismtype": "ContactMechanismType",
	    "communicationevent_partyrelationship": "PartyRelationship",
	    "communicationevent_communicationeventstatustype": "CommunicationEventStatusType",
	    "communicationevent_name": "Name",
	    "communicationevent_description": "Description",
	    "communicationevent_description": "Description",
	    "communicationevent_fromemail": "From Email",
	    "communicationevent_toemail": "To Email",
	    "communicationevent_fromphone": "From Phone",
	    "communicationevent_tophone": "To Phone",
	    "communicationevent_subject": "Subject",
	    "communicationevent_content": "Content",
	    "communicationevent_startdate": "Start Date",
	    "communicationevent_enddate": "End Date",
	    "communicationevent_partycases": "PartyCases",
	    "communicationevent_communicationeventworkefforts": "CommunicationEventWorkEfforts",
	    "communicationevent_id": "Id",
	    "communicationevent_code": "Code",
	    "communicationevent_effectivedt": "Effective Date",
	    "communicationevent_recst": "Status",
        "communicationevent_createddt": "Date Created",
		"communicationevent_createdbyusr": "Created By",
		"communicationevent_lastmodifieddt": "Last Modified",
		"communicationevent_lastmodifiedusr": "Last Modified By",
    	/* Party user strings*/
    	"party": "Party",
	    "party_partytype": "PartyType",
	    "party_name": "Name",
	    "party_description": "Description",
	    "party_customers": "Customers",
	    "party_partyclassifications": "PartyClassifications",
	    "party_partyroles": "PartyRoles",
	    "party_persons": "Persons",
	    "party_caseroles": "CaseRoles",
	    "party_paymentmethodtypeproviders": "PaymentMethodTypeProviders",
	    "party_partycontactmechanisms": "PartyContactMechanisms",
	    "party_billingaccountroles": "BillingAccountRoles",
	    "party_organizations": "Organizations",
	    "party_invoiceroles": "InvoiceRoles",
	    "party_paymentsfortopartyid": "PaymentsForToPartyId",
	    "party_paymentsforfrompartyid": "PaymentsForFromPartyId",
	    "party_invoicesforfrompartyid": "InvoicesForFromPartyId",
	    "party_invoicesfortopartyid": "InvoicesForToPartyId",
	    "party_customerblacklists": "CustomerBlacklists",
	    "party_id": "Id",
	    "party_code": "Code",
	    "party_effectivedt": "Effective Date",
	    "party_recst": "Status",
        "party_createddt": "Date Created",
		"party_createdbyusr": "Created By",
		"party_lastmodifieddt": "Last Modified",
		"party_lastmodifiedusr": "Last Modified By",
    	/* InvoiceStatus user strings*/
    	"invoicestatus": "Invoice Status",
	    "invoicestatus_invoicestatustype": "InvoiceStatusType",
	    "invoicestatus_invoice": "Invoice",
	    "invoicestatus_name": "Name",
	    "invoicestatus_description": "Description",
	    "invoicestatus_id": "Id",
	    "invoicestatus_code": "Code",
	    "invoicestatus_effectivedt": "Effective Date",
	    "invoicestatus_recst": "Status",
        "invoicestatus_createddt": "Date Created",
		"invoicestatus_createdbyusr": "Created By",
		"invoicestatus_lastmodifieddt": "Last Modified",
		"invoicestatus_lastmodifiedusr": "Last Modified By",
    	/* PartyContactMechanismPurpose user strings*/
    	"partycontactmechanismpurpose": "Party Contact Mechanism Purpose",
	    "partycontactmechanismpurpose_contactmechanismpurposetype": "ContactMechanismPurposeType",
	    "partycontactmechanismpurpose_contactmechanism": "ContactMechanism",
	    "partycontactmechanismpurpose_fromdt": "FromDt",
	    "partycontactmechanismpurpose_todt": "ToDt",
	    "partycontactmechanismpurpose_name": "Name",
	    "partycontactmechanismpurpose_description": "Description",
	    "partycontactmechanismpurpose_id": "Id",
	    "partycontactmechanismpurpose_code": "Code",
	    "partycontactmechanismpurpose_effectivedt": "Effective Date",
	    "partycontactmechanismpurpose_recst": "Status",
        "partycontactmechanismpurpose_createddt": "Date Created",
		"partycontactmechanismpurpose_createdbyusr": "Created By",
		"partycontactmechanismpurpose_lastmodifieddt": "Last Modified",
		"partycontactmechanismpurpose_lastmodifiedusr": "Last Modified By",
    	/* ProductOrder user strings*/
    	"productorder": "Product Order",
	    "productorder_productordertype": "ProductOrderType",
	    "productorder_name": "Name",
	    "productorder_description": "Description",
	    "productorder_orderdt": "OrderDt",
	    "productorder_productorderitems": "ProductOrderItems",
	    "productorder_id": "Id",
	    "productorder_code": "Code",
	    "productorder_effectivedt": "Effective Date",
	    "productorder_recst": "Status",
        "productorder_createddt": "Date Created",
		"productorder_createdbyusr": "Created By",
		"productorder_lastmodifieddt": "Last Modified",
		"productorder_lastmodifiedusr": "Last Modified By",
    	/* Invoice user strings*/
    	"invoice": "Invoice",
	    "invoice_invoicetype": "InvoiceType",
	    "invoice_partybytopartyid": "PartyByToPartyId",
	    "invoice_contactmechanism": "ContactMechanism",
	    "invoice_partybyfrompartyid": "PartyByFromPartyId",
	    "invoice_invoiceterm": "InvoiceTerm",
	    "invoice_message": "Message",
	    "invoice_description": "Description",
	    "invoice_invoicedt": "InvoiceDt",
	    "invoice_invoicestatuses": "InvoiceStatuses",
	    "invoice_invoiceroles": "InvoiceRoles",
	    "invoice_invoiceitems": "InvoiceItems",
	    "invoice_id": "Id",
	    "invoice_code": "Code",
	    "invoice_effectivedt": "Effective Date",
	    "invoice_recst": "Status",
        "invoice_createddt": "Date Created",
		"invoice_createdbyusr": "Created By",
		"invoice_lastmodifieddt": "Last Modified",
		"invoice_lastmodifiedusr": "Last Modified By",
    	/* InvoiceItem user strings*/
    	"invoiceitem": "Invoice Item",
	    "invoiceitem_invoiceitemtype": "InvoiceItemType",
	    "invoiceitem_invoiceitemcategory": "InvoiceItemCategory",
	    "invoiceitem_product": "Product",
	    "invoiceitem_productfeature": "ProductFeature",
	    "invoiceitem_invoice": "Invoice",
	    "invoiceitem_name": "Name",
	    "invoiceitem_description": "Description",
	    "invoiceitem_taxablefg": "TaxableFg",
	    "invoiceitem_quantity": "Quantity",
	    "invoiceitem_amount": "Amount",
	    "invoiceitem_orderitembillings": "OrderItemBillings",
	    "invoiceitem_paymentapplications": "PaymentApplications",
	    "invoiceitem_id": "Id",
	    "invoiceitem_code": "Code",
	    "invoiceitem_effectivedt": "Effective Date",
	    "invoiceitem_recst": "Status",
        "invoiceitem_createddt": "Date Created",
		"invoiceitem_createdbyusr": "Created By",
		"invoiceitem_lastmodifieddt": "Last Modified",
		"invoiceitem_lastmodifiedusr": "Last Modified By",
    	/* InvoiceStatusType user strings*/
    	"invoicestatustype": "Invoice Status Type",
	    "invoicestatustype_name": "Name",
	    "invoicestatustype_description": "Description",
	    "invoicestatustype_invoicestatuses": "InvoiceStatuses",
	    "invoicestatustype_id": "Id",
	    "invoicestatustype_code": "Code",
	    "invoicestatustype_effectivedt": "Effective Date",
	    "invoicestatustype_recst": "Status",
        "invoicestatustype_createddt": "Date Created",
		"invoicestatustype_createdbyusr": "Created By",
		"invoicestatustype_lastmodifieddt": "Last Modified",
		"invoicestatustype_lastmodifiedusr": "Last Modified By",
    	/* ProductFeatureCategory user strings*/
    	"productfeaturecategory": "Product Feature Category",
	    "productfeaturecategory_name": "Name",
	    "productfeaturecategory_description": "Description",
	    "productfeaturecategory_productfeatures": "ProductFeatures",
	    "productfeaturecategory_id": "Id",
	    "productfeaturecategory_code": "Code",
	    "productfeaturecategory_effectivedt": "Effective Date",
	    "productfeaturecategory_recst": "Status",
        "productfeaturecategory_createddt": "Date Created",
		"productfeaturecategory_createdbyusr": "Created By",
		"productfeaturecategory_lastmodifieddt": "Last Modified",
		"productfeaturecategory_lastmodifiedusr": "Last Modified By",
    	/* CommunicationEventPurpose user strings*/
    	"communicationeventpurpose": "Communication Event Purpose",
	    "communicationeventpurpose_communicationeventpurposetype": "CommunicationEventPurposeType",
	    "communicationeventpurpose_name": "Name",
	    "communicationeventpurpose_description": "Description",
	    "communicationeventpurpose_communicationevents": "CommunicationEvents",
	    "communicationeventpurpose_id": "Id",
	    "communicationeventpurpose_code": "Code",
	    "communicationeventpurpose_effectivedt": "Effective Date",
	    "communicationeventpurpose_recst": "Status",
        "communicationeventpurpose_createddt": "Date Created",
		"communicationeventpurpose_createdbyusr": "Created By",
		"communicationeventpurpose_lastmodifieddt": "Last Modified",
		"communicationeventpurpose_lastmodifiedusr": "Last Modified By",
    	/* Organization user strings*/
    	"organization": "Organization",
	    "organization_party": "Party",
	    "organization_taxidno": "TaxIdNo",
	    "organization_id": "Id",
	    "organization_code": "Code",
	    "organization_effectivedt": "Effective Date",
	    "organization_recst": "Status",
        "organization_createddt": "Date Created",
		"organization_createdbyusr": "Created By",
		"organization_lastmodifieddt": "Last Modified",
		"organization_lastmodifiedusr": "Last Modified By",
    	/* CaseRoleType user strings*/
    	"caseroletype": "Case Role Type",
	    "caseroletype_name": "Name",
	    "caseroletype_description": "Description",
	    "caseroletype_caseroles": "CaseRoles",
	    "caseroletype_id": "Id",
	    "caseroletype_code": "Code",
	    "caseroletype_effectivedt": "Effective Date",
	    "caseroletype_recst": "Status",
        "caseroletype_createddt": "Date Created",
		"caseroletype_createdbyusr": "Created By",
		"caseroletype_lastmodifieddt": "Last Modified",
		"caseroletype_lastmodifiedusr": "Last Modified By",
    	/* Payment user strings*/
    	"payment": "Payment",
	    "payment_paymenttype": "PaymentType",
	    "payment_partybytopartyid": "PartyByToPartyId",
	    "payment_partybyfrompartyid": "PartyByFromPartyId",
	    "payment_paymentmethodtypeprovider": "PaymentMethodTypeProvider",
	    "payment_paymentmethodtype": "PaymentMethodType",
	    "payment_name": "Name",
	    "payment_description": "Description",
	    "payment_comment": "Comment",
	    "payment_amount": "Amount",
	    "payment_paymentapplications": "PaymentApplications",
	    "payment_id": "Id",
	    "payment_code": "Code",
	    "payment_effectivedt": "Effective Date",
	    "payment_recst": "Status",
        "payment_createddt": "Date Created",
		"payment_createdbyusr": "Created By",
		"payment_lastmodifieddt": "Last Modified",
		"payment_lastmodifiedusr": "Last Modified By",
    	/* PaymentMethodTypeProvider user strings*/
    	"paymentmethodtypeprovider": "Payment Method Type Provider",
	    "paymentmethodtypeprovider_paymentmethodtype": "PaymentMethodType",
	    "paymentmethodtypeprovider_party": "Party",
	    "paymentmethodtypeprovider_name": "Name",
	    "paymentmethodtypeprovider_description": "Description",
	    "paymentmethodtypeprovider_fromdt": "FromDt",
	    "paymentmethodtypeprovider_thrudt": "ThruDt",
	    "paymentmethodtypeprovider_payments": "Payments",
	    "paymentmethodtypeprovider_id": "Id",
	    "paymentmethodtypeprovider_code": "Code",
	    "paymentmethodtypeprovider_effectivedt": "Effective Date",
	    "paymentmethodtypeprovider_recst": "Status",
        "paymentmethodtypeprovider_createddt": "Date Created",
		"paymentmethodtypeprovider_createdbyusr": "Created By",
		"paymentmethodtypeprovider_lastmodifieddt": "Last Modified",
		"paymentmethodtypeprovider_lastmodifiedusr": "Last Modified By",
    	/* WorkEffortType user strings*/
    	"workefforttype": "Work Effort",
	    "workefforttype_name": "Name",
	    "workefforttype_description": "Description",
	    "workefforttype_workefforts": "WorkEfforts",
	    "workefforttype_id": "Id",
	    "workefforttype_code": "Code",
	    "workefforttype_effectivedt": "Effective Date",
	    "workefforttype_recst": "Status",
        "workefforttype_createddt": "Date Created",
		"workefforttype_createdbyusr": "Created By",
		"workefforttype_lastmodifieddt": "Last Modified",
		"workefforttype_lastmodifiedusr": "Last Modified By",
    	/* ProductOrderItemType user strings*/
    	"productorderitemtype": "Product Order Item Type",
	    "productorderitemtype_name": "Name",
	    "productorderitemtype_description": "Description",
	    "productorderitemtype_productorderitems": "ProductOrderItems",
	    "productorderitemtype_id": "Id",
	    "productorderitemtype_code": "Code",
	    "productorderitemtype_effectivedt": "Effective Date",
	    "productorderitemtype_recst": "Status",
        "productorderitemtype_createddt": "Date Created",
		"productorderitemtype_createdbyusr": "Created By",
		"productorderitemtype_lastmodifieddt": "Last Modified",
		"productorderitemtype_lastmodifiedusr": "Last Modified By",
    	/* GeoBoundryAssociation user strings*/
    	"geoboundryassociation": "Geo Boundry Association",
	    "geoboundryassociation_geoboundrybytogeoid": "GeoBoundryByToGeoId",
	    "geoboundryassociation_geoboundrybyfromgeoid": "GeoBoundryByFromGeoId",
	    "geoboundryassociation_description": "Description",
	    "geoboundryassociation_id": "Id",
	    "geoboundryassociation_code": "Code",
	    "geoboundryassociation_effectivedt": "Effective Date",
	    "geoboundryassociation_recst": "Status",
        "geoboundryassociation_createddt": "Date Created",
		"geoboundryassociation_createdbyusr": "Created By",
		"geoboundryassociation_lastmodifieddt": "Last Modified",
		"geoboundryassociation_lastmodifiedusr": "Last Modified By",
    	/* GeoBoundaryType user strings*/
    	"geoboundarytype": "Geo Boundry Type",
	    "geoboundarytype_geoboundarytype": "GeoBoundaryType",
	    "geoboundarytype_name": "Name",
	    "geoboundarytype_description": "Description",
	    "geoboundarytype_geoboundarytypes": "GeoBoundaryTypes",
	    "geoboundarytype_geoboundries": "GeoBoundries",
	    "geoboundarytype_id": "Id",
	    "geoboundarytype_code": "Code",
	    "geoboundarytype_effectivedt": "Effective Date",
	    "geoboundarytype_recst": "Status",
        "geoboundarytype_createddt": "Date Created",
		"geoboundarytype_createdbyusr": "Created By",
		"geoboundarytype_lastmodifieddt": "Last Modified",
		"geoboundarytype_lastmodifiedusr": "Last Modified By",
   
		
    }
});