package com.nathanclaire.alantra.base.model;
// Generated May 21, 2013 11:46:57 AM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TempRelatedActivity generated by hbm2java
 */
@Entity
@Table(name="TEMP_RELATED_ACTIVITY"
    ,catalog="alantra"
)
public class TempRelatedActivity  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8335948813202415010L;
	private Integer id;
     private String sourceActivity;
     private String destinationActivity;
     private String relationshipTy;

    public TempRelatedActivity() {
    }

    public TempRelatedActivity(String sourceActivity, String destinationActivity, String relationshipTy) {
       this.sourceActivity = sourceActivity;
       this.destinationActivity = destinationActivity;
       this.relationshipTy = relationshipTy;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="SOURCE_ACTIVITY", nullable=false, length=75)
    public String getSourceActivity() {
        return this.sourceActivity;
    }
    
    public void setSourceActivity(String sourceActivity) {
        this.sourceActivity = sourceActivity;
    }

    
    @Column(name="DESTINATION_ACTIVITY", nullable=false, length=75)
    public String getDestinationActivity() {
        return this.destinationActivity;
    }
    
    public void setDestinationActivity(String destinationActivity) {
        this.destinationActivity = destinationActivity;
    }

    
    @Column(name="RELATIONSHIP_TY", nullable=false, length=75)
    public String getRelationshipTy() {
        return this.relationshipTy;
    }
    
    public void setRelationshipTy(String relationshipTy) {
        this.relationshipTy = relationshipTy;
    }




}


