package com.nathanclaire.alantra.customer.model;
// Generated Jun 25, 2013 10:59:49 AM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * CustomerType generated by hbm2java
 */
@Entity
@Table(name="CUSTOMER_TYPE"
    ,catalog="alantra"
    , uniqueConstraints = @UniqueConstraint(columnNames="CODE") 
)
public class CustomerType  implements java.io.Serializable {


     private Integer id;
     private CustomerCategory customerCategory;
     private String name;
     private String description;
     private String code;
     private Date effectiveDt;
     private char recSt;
     private Integer versionNo;
     private Date rowTs;
     private Date createdDt;
     private String createdByUsr;
     private Date lastModifiedDt;
     private String lastModifiedUsr;
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<CustomerTypeTransactionLimit> customerTypeTransactionLimits = new HashSet<CustomerTypeTransactionLimit>(0);
     private Set<CustomerTypeNotificationChannel> customerTypeNotificationChannels = new HashSet<CustomerTypeNotificationChannel>(0);

    public CustomerType() {
    }

	
    public CustomerType(CustomerCategory customerCategory, String name, String code, Date effectiveDt, char recSt, Date createdDt, String createdByUsr) {
        this.customerCategory = customerCategory;
        this.name = name;
        this.code = code;
        this.effectiveDt = effectiveDt;
        this.recSt = recSt;
        this.createdDt = createdDt;
        this.createdByUsr = createdByUsr;
    }
    public CustomerType(CustomerCategory customerCategory, String name, String description, String code, Date effectiveDt, char recSt, Integer versionNo, Date rowTs, Date createdDt, String createdByUsr, Date lastModifiedDt, String lastModifiedUsr, Set<Customer> customers, Set<CustomerTypeTransactionLimit> customerTypeTransactionLimits, Set<CustomerTypeNotificationChannel> customerTypeNotificationChannels) {
       this.customerCategory = customerCategory;
       this.name = name;
       this.description = description;
       this.code = code;
       this.effectiveDt = effectiveDt;
       this.recSt = recSt;
       this.versionNo = versionNo;
       this.rowTs = rowTs;
       this.createdDt = createdDt;
       this.createdByUsr = createdByUsr;
       this.lastModifiedDt = lastModifiedDt;
       this.lastModifiedUsr = lastModifiedUsr;
       this.customers = customers;
       this.customerTypeTransactionLimits = customerTypeTransactionLimits;
       this.customerTypeNotificationChannels = customerTypeNotificationChannels;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CUST_CAT_ID", nullable=false)
    public CustomerCategory getCustomerCategory() {
        return this.customerCategory;
    }
    
    public void setCustomerCategory(CustomerCategory customerCategory) {
        this.customerCategory = customerCategory;
    }

    
    @Column(name="NAME", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="DESCRIPTION", length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="CODE", unique=true, nullable=false, length=35)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EFFECTIVE_DT", nullable=false, length=10)
    public Date getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Date effectiveDt) {
        this.effectiveDt = effectiveDt;
    }

    
    @Column(name="REC_ST", nullable=false, length=1)
    public char getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(char recSt) {
        this.recSt = recSt;
    }

    
    @Column(name="VERSION_NO")
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ROW_TS", length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CREATED_DT", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }

    
    @Column(name="CREATED_BY_USR", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_MODIFIED_DT", length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }

    
    @Column(name="LAST_MODIFIED_USR", length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerType")
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerType")
    public Set<CustomerTypeTransactionLimit> getCustomerTypeTransactionLimits() {
        return this.customerTypeTransactionLimits;
    }
    
    public void setCustomerTypeTransactionLimits(Set<CustomerTypeTransactionLimit> customerTypeTransactionLimits) {
        this.customerTypeTransactionLimits = customerTypeTransactionLimits;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerType")
    public Set<CustomerTypeNotificationChannel> getCustomerTypeNotificationChannels() {
        return this.customerTypeNotificationChannels;
    }
    
    public void setCustomerTypeNotificationChannels(Set<CustomerTypeNotificationChannel> customerTypeNotificationChannels) {
        this.customerTypeNotificationChannels = customerTypeNotificationChannels;
    }




}


